# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .apikey import *
from .dashboard import *
from .dataintegration import *
from .ingestionkey import *
from .logspipeline import *
from .metricsaggregation import *
from .monitor import *
from .policy import *
from .provider import *
from .secret import *
from .serviceaccount import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import groundcover_groundcover.config as __config
    config = __config
else:
    config = _utilities.lazy_import('groundcover_groundcover.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "groundcover",
  "mod": "index/apikey",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/apikey:Apikey": "Apikey"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/dashboard",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/dashboard:Dashboard": "Dashboard"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/dataintegration",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/dataintegration:Dataintegration": "Dataintegration"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/ingestionkey",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/ingestionkey:Ingestionkey": "Ingestionkey"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/logspipeline",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/logspipeline:Logspipeline": "Logspipeline"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/metricsaggregation",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/metricsaggregation:Metricsaggregation": "Metricsaggregation"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/monitor",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/monitor:Monitor": "Monitor"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/policy",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/secret",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/secret:Secret": "Secret"
  }
 },
 {
  "pkg": "groundcover",
  "mod": "index/serviceaccount",
  "fqn": "groundcover_groundcover",
  "classes": {
   "groundcover:index/serviceaccount:Serviceaccount": "Serviceaccount"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "groundcover",
  "token": "pulumi:providers:groundcover",
  "fqn": "groundcover_groundcover",
  "class": "Provider"
 }
]
"""
)
