# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DashboardArgs', 'Dashboard']

@pulumi.input_type
class DashboardArgs:
    def __init__(__self__, *,
                 preset: pulumi.Input[_builtins.str],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 override: Optional[pulumi.Input[_builtins.bool]] = None,
                 team: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Dashboard resource.
        :param pulumi.Input[_builtins.str] preset: The preset configuration for the dashboard.
        :param pulumi.Input[_builtins.str] description: The description of the dashboard.
        :param pulumi.Input[_builtins.str] name: The name of the dashboard.
        :param pulumi.Input[_builtins.bool] override: Whether to override the dashboard on update.
        :param pulumi.Input[_builtins.str] team: The team that owns the dashboard.
        """
        pulumi.set(__self__, "preset", preset)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if override is not None:
            pulumi.set(__self__, "override", override)
        if team is not None:
            pulumi.set(__self__, "team", team)

    @_builtins.property
    @pulumi.getter
    def preset(self) -> pulumi.Input[_builtins.str]:
        """
        The preset configuration for the dashboard.
        """
        return pulumi.get(self, "preset")

    @preset.setter
    def preset(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "preset", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the dashboard.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the dashboard.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def override(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to override the dashboard on update.
        """
        return pulumi.get(self, "override")

    @override.setter
    def override(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "override", value)

    @_builtins.property
    @pulumi.getter
    def team(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The team that owns the dashboard.
        """
        return pulumi.get(self, "team")

    @team.setter
    def team(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team", value)


@pulumi.input_type
class _DashboardState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 override: Optional[pulumi.Input[_builtins.bool]] = None,
                 owner: Optional[pulumi.Input[_builtins.str]] = None,
                 preset: Optional[pulumi.Input[_builtins.str]] = None,
                 revision_number: Optional[pulumi.Input[_builtins.int]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 team: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Dashboard resources.
        :param pulumi.Input[_builtins.str] description: The description of the dashboard.
        :param pulumi.Input[_builtins.str] name: The name of the dashboard.
        :param pulumi.Input[_builtins.bool] override: Whether to override the dashboard on update.
        :param pulumi.Input[_builtins.str] owner: The owner of the dashboard.
        :param pulumi.Input[_builtins.str] preset: The preset configuration for the dashboard.
        :param pulumi.Input[_builtins.int] revision_number: The revision number of the dashboard.
        :param pulumi.Input[_builtins.str] status: The status of the dashboard.
        :param pulumi.Input[_builtins.str] team: The team that owns the dashboard.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if override is not None:
            pulumi.set(__self__, "override", override)
        if owner is not None:
            pulumi.set(__self__, "owner", owner)
        if preset is not None:
            pulumi.set(__self__, "preset", preset)
        if revision_number is not None:
            pulumi.set(__self__, "revision_number", revision_number)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if team is not None:
            pulumi.set(__self__, "team", team)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the dashboard.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the dashboard.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def override(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to override the dashboard on update.
        """
        return pulumi.get(self, "override")

    @override.setter
    def override(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "override", value)

    @_builtins.property
    @pulumi.getter
    def owner(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The owner of the dashboard.
        """
        return pulumi.get(self, "owner")

    @owner.setter
    def owner(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "owner", value)

    @_builtins.property
    @pulumi.getter
    def preset(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The preset configuration for the dashboard.
        """
        return pulumi.get(self, "preset")

    @preset.setter
    def preset(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "preset", value)

    @_builtins.property
    @pulumi.getter(name="revisionNumber")
    def revision_number(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The revision number of the dashboard.
        """
        return pulumi.get(self, "revision_number")

    @revision_number.setter
    def revision_number(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "revision_number", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The status of the dashboard.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def team(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The team that owns the dashboard.
        """
        return pulumi.get(self, "team")

    @team.setter
    def team(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team", value)


@pulumi.type_token("groundcover:index/dashboard:Dashboard")
class Dashboard(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 override: Optional[pulumi.Input[_builtins.bool]] = None,
                 preset: Optional[pulumi.Input[_builtins.str]] = None,
                 team: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Dashboard resource for managing groundcover dashboards.

        ## Example Usage

        ```python
        import pulumi
        import groundcover_groundcover as groundcover
        import json

        config = pulumi.Config()
        groundcover_api_key = config.require("groundcoverApiKey")
        groundcover_backend_id = config.require("groundcoverBackendId")
        # Example Dashboard: Basic metrics dashboard
        metrics_dashboard = groundcover.Dashboard("metricsDashboard",
            description="Example dashboard showing system metrics",
            team="platform",
            preset=json.dumps({
                "duration": "Last 1 hour",
                "layout": [
                    {
                        "id": "A",
                        "x": 0,
                        "y": 0,
                        "w": 12,
                        "h": 4,
                        "minH": 2,
                    },
                    {
                        "id": "B",
                        "x": 0,
                        "y": 4,
                        "w": 6,
                        "h": 4,
                        "minH": 2,
                    },
                    {
                        "id": "C",
                        "x": 6,
                        "y": 4,
                        "w": 6,
                        "h": 4,
                        "minH": 2,
                    },
                ],
                "widgets": [
                    {
                        "id": "A",
                        "type": "widget",
                        "name": "CPU Usage",
                        "queries": [{
                            "id": "A",
                            "expr": "avg(rate(container_cpu_usage_seconds_total[5m])) * 100",
                            "dataType": "metrics",
                            "step": None,
                            "editorMode": "builder",
                        }],
                        "visualizationConfig": {
                            "type": "time-series",
                        },
                    },
                    {
                        "id": "B",
                        "type": "widget",
                        "name": "Memory Usage",
                        "queries": [{
                            "id": "B",
                            "expr": "avg(container_memory_usage_bytes)",
                            "dataType": "metrics",
                            "step": None,
                            "editorMode": "builder",
                        }],
                        "visualizationConfig": {
                            "type": "gauge",
                        },
                    },
                    {
                        "id": "C",
                        "type": "text",
                        "html": "<h3>System Metrics</h3><p>This dashboard shows key system metrics including CPU and memory usage.</p>",
                    },
                ],
                "variables": {},
                "schemaVersion": 3,
            }))
        # Example Dashboard: Simple monitoring dashboard
        simple_dashboard = groundcover.Dashboard("simpleDashboard", preset=json.dumps({
            "duration": "Last 30 minutes",
            "layout": [{
                "id": "widget1",
                "x": 0,
                "y": 0,
                "w": 12,
                "h": 6,
                "minH": 3,
            }],
            "widgets": [{
                "id": "widget1",
                "type": "widget",
                "name": "Request Rate",
                "queries": [{
                    "id": "query1",
                    "expr": "sum(rate(http_requests_total[5m]))",
                    "dataType": "metrics",
                    "step": None,
                    "editorMode": "code",
                }],
                "visualizationConfig": {
                    "type": "time-series",
                    "config": {
                        "showLegend": True,
                        "unit": "ops",
                    },
                },
            }],
            "variables": {},
            "schemaVersion": 3,
        }))
        pulumi.export("metricsDashboardId", metrics_dashboard.id)
        pulumi.export("metricsDashboardOwner", metrics_dashboard.owner)
        pulumi.export("simpleDashboardId", simple_dashboard.id)
        pulumi.export("simpleDashboardOwner", simple_dashboard.owner)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the dashboard.
        :param pulumi.Input[_builtins.str] name: The name of the dashboard.
        :param pulumi.Input[_builtins.bool] override: Whether to override the dashboard on update.
        :param pulumi.Input[_builtins.str] preset: The preset configuration for the dashboard.
        :param pulumi.Input[_builtins.str] team: The team that owns the dashboard.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DashboardArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Dashboard resource for managing groundcover dashboards.

        ## Example Usage

        ```python
        import pulumi
        import groundcover_groundcover as groundcover
        import json

        config = pulumi.Config()
        groundcover_api_key = config.require("groundcoverApiKey")
        groundcover_backend_id = config.require("groundcoverBackendId")
        # Example Dashboard: Basic metrics dashboard
        metrics_dashboard = groundcover.Dashboard("metricsDashboard",
            description="Example dashboard showing system metrics",
            team="platform",
            preset=json.dumps({
                "duration": "Last 1 hour",
                "layout": [
                    {
                        "id": "A",
                        "x": 0,
                        "y": 0,
                        "w": 12,
                        "h": 4,
                        "minH": 2,
                    },
                    {
                        "id": "B",
                        "x": 0,
                        "y": 4,
                        "w": 6,
                        "h": 4,
                        "minH": 2,
                    },
                    {
                        "id": "C",
                        "x": 6,
                        "y": 4,
                        "w": 6,
                        "h": 4,
                        "minH": 2,
                    },
                ],
                "widgets": [
                    {
                        "id": "A",
                        "type": "widget",
                        "name": "CPU Usage",
                        "queries": [{
                            "id": "A",
                            "expr": "avg(rate(container_cpu_usage_seconds_total[5m])) * 100",
                            "dataType": "metrics",
                            "step": None,
                            "editorMode": "builder",
                        }],
                        "visualizationConfig": {
                            "type": "time-series",
                        },
                    },
                    {
                        "id": "B",
                        "type": "widget",
                        "name": "Memory Usage",
                        "queries": [{
                            "id": "B",
                            "expr": "avg(container_memory_usage_bytes)",
                            "dataType": "metrics",
                            "step": None,
                            "editorMode": "builder",
                        }],
                        "visualizationConfig": {
                            "type": "gauge",
                        },
                    },
                    {
                        "id": "C",
                        "type": "text",
                        "html": "<h3>System Metrics</h3><p>This dashboard shows key system metrics including CPU and memory usage.</p>",
                    },
                ],
                "variables": {},
                "schemaVersion": 3,
            }))
        # Example Dashboard: Simple monitoring dashboard
        simple_dashboard = groundcover.Dashboard("simpleDashboard", preset=json.dumps({
            "duration": "Last 30 minutes",
            "layout": [{
                "id": "widget1",
                "x": 0,
                "y": 0,
                "w": 12,
                "h": 6,
                "minH": 3,
            }],
            "widgets": [{
                "id": "widget1",
                "type": "widget",
                "name": "Request Rate",
                "queries": [{
                    "id": "query1",
                    "expr": "sum(rate(http_requests_total[5m]))",
                    "dataType": "metrics",
                    "step": None,
                    "editorMode": "code",
                }],
                "visualizationConfig": {
                    "type": "time-series",
                    "config": {
                        "showLegend": True,
                        "unit": "ops",
                    },
                },
            }],
            "variables": {},
            "schemaVersion": 3,
        }))
        pulumi.export("metricsDashboardId", metrics_dashboard.id)
        pulumi.export("metricsDashboardOwner", metrics_dashboard.owner)
        pulumi.export("simpleDashboardId", simple_dashboard.id)
        pulumi.export("simpleDashboardOwner", simple_dashboard.owner)
        ```

        :param str resource_name: The name of the resource.
        :param DashboardArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DashboardArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 override: Optional[pulumi.Input[_builtins.bool]] = None,
                 preset: Optional[pulumi.Input[_builtins.str]] = None,
                 team: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DashboardArgs.__new__(DashboardArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["override"] = override
            if preset is None and not opts.urn:
                raise TypeError("Missing required property 'preset'")
            __props__.__dict__["preset"] = preset
            __props__.__dict__["team"] = team
            __props__.__dict__["owner"] = None
            __props__.__dict__["revision_number"] = None
            __props__.__dict__["status"] = None
        super(Dashboard, __self__).__init__(
            'groundcover:index/dashboard:Dashboard',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            override: Optional[pulumi.Input[_builtins.bool]] = None,
            owner: Optional[pulumi.Input[_builtins.str]] = None,
            preset: Optional[pulumi.Input[_builtins.str]] = None,
            revision_number: Optional[pulumi.Input[_builtins.int]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            team: Optional[pulumi.Input[_builtins.str]] = None) -> 'Dashboard':
        """
        Get an existing Dashboard resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the dashboard.
        :param pulumi.Input[_builtins.str] name: The name of the dashboard.
        :param pulumi.Input[_builtins.bool] override: Whether to override the dashboard on update.
        :param pulumi.Input[_builtins.str] owner: The owner of the dashboard.
        :param pulumi.Input[_builtins.str] preset: The preset configuration for the dashboard.
        :param pulumi.Input[_builtins.int] revision_number: The revision number of the dashboard.
        :param pulumi.Input[_builtins.str] status: The status of the dashboard.
        :param pulumi.Input[_builtins.str] team: The team that owns the dashboard.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DashboardState.__new__(_DashboardState)

        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["override"] = override
        __props__.__dict__["owner"] = owner
        __props__.__dict__["preset"] = preset
        __props__.__dict__["revision_number"] = revision_number
        __props__.__dict__["status"] = status
        __props__.__dict__["team"] = team
        return Dashboard(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the dashboard.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the dashboard.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def override(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to override the dashboard on update.
        """
        return pulumi.get(self, "override")

    @_builtins.property
    @pulumi.getter
    def owner(self) -> pulumi.Output[_builtins.str]:
        """
        The owner of the dashboard.
        """
        return pulumi.get(self, "owner")

    @_builtins.property
    @pulumi.getter
    def preset(self) -> pulumi.Output[_builtins.str]:
        """
        The preset configuration for the dashboard.
        """
        return pulumi.get(self, "preset")

    @_builtins.property
    @pulumi.getter(name="revisionNumber")
    def revision_number(self) -> pulumi.Output[_builtins.int]:
        """
        The revision number of the dashboard.
        """
        return pulumi.get(self, "revision_number")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        The status of the dashboard.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def team(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The team that owns the dashboard.
        """
        return pulumi.get(self, "team")

