# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DataintegrationArgs', 'Dataintegration']

@pulumi.input_type
class DataintegrationArgs:
    def __init__(__self__, *,
                 config: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Dataintegration resource.
        :param pulumi.Input[_builtins.str] config: The JSON configuration for the data integration.
        :param pulumi.Input[_builtins.str] type: The type of data integration (e.g., 'cloudwatch', etc.).
        :param pulumi.Input[_builtins.str] cluster: The cluster where the data integration runs. If unspecified, it will run in the backend.
        :param pulumi.Input[_builtins.bool] is_paused: Whether the data integration is paused. Default: `false`.
        """
        pulumi.set(__self__, "config", config)
        pulumi.set(__self__, "type", type)
        if cluster is not None:
            pulumi.set(__self__, "cluster", cluster)
        if is_paused is not None:
            pulumi.set(__self__, "is_paused", is_paused)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[_builtins.str]:
        """
        The JSON configuration for the data integration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        The type of data integration (e.g., 'cloudwatch', etc.).
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The cluster where the data integration runs. If unspecified, it will run in the backend.
        """
        return pulumi.get(self, "cluster")

    @cluster.setter
    def cluster(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster", value)

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the data integration is paused. Default: `false`.
        """
        return pulumi.get(self, "is_paused")

    @is_paused.setter
    def is_paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_paused", value)


@pulumi.input_type
class _DataintegrationState:
    def __init__(__self__, *,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 config: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 updated_at: Optional[pulumi.Input[_builtins.str]] = None,
                 updated_by: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Dataintegration resources.
        :param pulumi.Input[_builtins.str] cluster: The cluster where the data integration runs. If unspecified, it will run in the backend.
        :param pulumi.Input[_builtins.str] config: The JSON configuration for the data integration.
        :param pulumi.Input[_builtins.bool] is_paused: Whether the data integration is paused. Default: `false`.
        :param pulumi.Input[_builtins.str] type: The type of data integration (e.g., 'cloudwatch', etc.).
        :param pulumi.Input[_builtins.str] updated_at: The last update timestamp of the data integration configuration.
        :param pulumi.Input[_builtins.str] updated_by: The user who last updated the data integration configuration.
        """
        if cluster is not None:
            pulumi.set(__self__, "cluster", cluster)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if is_paused is not None:
            pulumi.set(__self__, "is_paused", is_paused)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if updated_by is not None:
            pulumi.set(__self__, "updated_by", updated_by)

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The cluster where the data integration runs. If unspecified, it will run in the backend.
        """
        return pulumi.get(self, "cluster")

    @cluster.setter
    def cluster(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The JSON configuration for the data integration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the data integration is paused. Default: `false`.
        """
        return pulumi.get(self, "is_paused")

    @is_paused.setter
    def is_paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_paused", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of data integration (e.g., 'cloudwatch', etc.).
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The last update timestamp of the data integration configuration.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter(name="updatedBy")
    def updated_by(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The user who last updated the data integration configuration.
        """
        return pulumi.get(self, "updated_by")

    @updated_by.setter
    def updated_by(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated_by", value)


@pulumi.type_token("groundcover:index/dataintegration:Dataintegration")
class Dataintegration(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 config: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        DataIntegration resource for managing groundcover's integrations with external services such as cloud providers, databases and more. This resource is composed of general metadata on the integration and a specific configuration per data source. Navigate to the relevant nested schema according to your specific needs.

        ## Example Usage

        ```python
        import pulumi
        import groundcover_groundcover as groundcover
        import json

        # Example: CloudWatch DataIntegration
        # For a full list of supported AWS metrics and statistics, visit the official CloudWatch documentation:
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html
        cloudwatch_example = groundcover.Dataintegration("cloudwatchExample",
            type="cloudwatch",
            config=json.dumps({
                "name": "test-cloudwatch",
                "version": 1,
                "stsRegion": "us-east-1",
                "regions": [
                    "us-east-1",
                    "us-east-2",
                ],
                "roleArn": "arn:aws:iam::123456789012:role/test-role",
                "awsMetrics": [{
                    "namespace": "AWS/EC2",
                    "metrics": [{
                        "name": "CPUUtilization",
                        "statistics": ["Average"],
                    }],
                }],
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
                "scrapeInterval": 300000000000,
                "exporters": ["prometheus"],
            }),
            is_paused=False)
        # Example: GCP Metrics DataIntegration
        # For a full list of supported GCP metrics, visit the official GCP documentation:
        # https://cloud.google.com/monitoring/api/metrics_gcp
        gcp_example = groundcover.Dataintegration("gcpExample",
            type="gcpmetrics",
            config=json.dumps({
                "name": "test-gcp",
                "version": 1,
                "enabled": True,
                "targetServiceAccount": "demo@gcp-demo-project.iam.gserviceaccount.com",
                "regions": ["us-west1"],
                "metricPrefixes": [
                    "cloudsql.googleapis.com",
                    "compute.googleapis.com",
                ],
                "projectIDs": ["gcp-demo-project"],
                "scrapeInterval": 300000000000,
                "exporters": ["prometheus"],
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
            }),
            is_paused=False)
        # Example: Azure Metrics DataIntegration
        # For a full list of supported Azure metrics, visit the official Azure Monitor documentation:
        # https://learn.microsoft.com/en-us/azure/azure-monitor/reference/metrics-index
        azure_example = groundcover.Dataintegration("azureExample",
            type="azuremetrics",
            config=json.dumps({
                "name": "Azure demo",
                "version": 1,
                "subscriptions": ["b3128f7e-54df-4d2e-9c3e-93a4f1f8c9a0"],
                "regions": ["australiaeast"],
                "azureMetrics": [{
                    "resourceType": "Microsoft.Compute/virtualMachines",
                    "metrics": [{
                        "name": "Available Memory Bytes",
                    }],
                    "aggregations": [
                        "Average",
                        "Maximum",
                        "Minimum",
                    ],
                }],
                "azureCloudEnvironment": "AzurePublicCloud",
                "scrapeInterval": 300000000000,
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
                "exporters": ["prometheus"],
            }),
            is_paused=False)
        pulumi.export("cloudwatchDataintegrationId", cloudwatch_example.id)
        pulumi.export("gcpmetricsDataintegrationId", gcp_example.id)
        pulumi.export("azuremetricsDataintegrationId", azure_example.id)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster: The cluster where the data integration runs. If unspecified, it will run in the backend.
        :param pulumi.Input[_builtins.str] config: The JSON configuration for the data integration.
        :param pulumi.Input[_builtins.bool] is_paused: Whether the data integration is paused. Default: `false`.
        :param pulumi.Input[_builtins.str] type: The type of data integration (e.g., 'cloudwatch', etc.).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DataintegrationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        DataIntegration resource for managing groundcover's integrations with external services such as cloud providers, databases and more. This resource is composed of general metadata on the integration and a specific configuration per data source. Navigate to the relevant nested schema according to your specific needs.

        ## Example Usage

        ```python
        import pulumi
        import groundcover_groundcover as groundcover
        import json

        # Example: CloudWatch DataIntegration
        # For a full list of supported AWS metrics and statistics, visit the official CloudWatch documentation:
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html
        cloudwatch_example = groundcover.Dataintegration("cloudwatchExample",
            type="cloudwatch",
            config=json.dumps({
                "name": "test-cloudwatch",
                "version": 1,
                "stsRegion": "us-east-1",
                "regions": [
                    "us-east-1",
                    "us-east-2",
                ],
                "roleArn": "arn:aws:iam::123456789012:role/test-role",
                "awsMetrics": [{
                    "namespace": "AWS/EC2",
                    "metrics": [{
                        "name": "CPUUtilization",
                        "statistics": ["Average"],
                    }],
                }],
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
                "scrapeInterval": 300000000000,
                "exporters": ["prometheus"],
            }),
            is_paused=False)
        # Example: GCP Metrics DataIntegration
        # For a full list of supported GCP metrics, visit the official GCP documentation:
        # https://cloud.google.com/monitoring/api/metrics_gcp
        gcp_example = groundcover.Dataintegration("gcpExample",
            type="gcpmetrics",
            config=json.dumps({
                "name": "test-gcp",
                "version": 1,
                "enabled": True,
                "targetServiceAccount": "demo@gcp-demo-project.iam.gserviceaccount.com",
                "regions": ["us-west1"],
                "metricPrefixes": [
                    "cloudsql.googleapis.com",
                    "compute.googleapis.com",
                ],
                "projectIDs": ["gcp-demo-project"],
                "scrapeInterval": 300000000000,
                "exporters": ["prometheus"],
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
            }),
            is_paused=False)
        # Example: Azure Metrics DataIntegration
        # For a full list of supported Azure metrics, visit the official Azure Monitor documentation:
        # https://learn.microsoft.com/en-us/azure/azure-monitor/reference/metrics-index
        azure_example = groundcover.Dataintegration("azureExample",
            type="azuremetrics",
            config=json.dumps({
                "name": "Azure demo",
                "version": 1,
                "subscriptions": ["b3128f7e-54df-4d2e-9c3e-93a4f1f8c9a0"],
                "regions": ["australiaeast"],
                "azureMetrics": [{
                    "resourceType": "Microsoft.Compute/virtualMachines",
                    "metrics": [{
                        "name": "Available Memory Bytes",
                    }],
                    "aggregations": [
                        "Average",
                        "Maximum",
                        "Minimum",
                    ],
                }],
                "azureCloudEnvironment": "AzurePublicCloud",
                "scrapeInterval": 300000000000,
                "labelSettings": {
                    "extraLabels": {
                        "env": "prod",
                    },
                },
                "exporters": ["prometheus"],
            }),
            is_paused=False)
        pulumi.export("cloudwatchDataintegrationId", cloudwatch_example.id)
        pulumi.export("gcpmetricsDataintegrationId", gcp_example.id)
        pulumi.export("azuremetricsDataintegrationId", azure_example.id)
        ```

        :param str resource_name: The name of the resource.
        :param DataintegrationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DataintegrationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 config: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DataintegrationArgs.__new__(DataintegrationArgs)

            __props__.__dict__["cluster"] = cluster
            if config is None and not opts.urn:
                raise TypeError("Missing required property 'config'")
            __props__.__dict__["config"] = config
            __props__.__dict__["is_paused"] = is_paused
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["updated_by"] = None
        super(Dataintegration, __self__).__init__(
            'groundcover:index/dataintegration:Dataintegration',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            cluster: Optional[pulumi.Input[_builtins.str]] = None,
            config: Optional[pulumi.Input[_builtins.str]] = None,
            is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None,
            updated_at: Optional[pulumi.Input[_builtins.str]] = None,
            updated_by: Optional[pulumi.Input[_builtins.str]] = None) -> 'Dataintegration':
        """
        Get an existing Dataintegration resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster: The cluster where the data integration runs. If unspecified, it will run in the backend.
        :param pulumi.Input[_builtins.str] config: The JSON configuration for the data integration.
        :param pulumi.Input[_builtins.bool] is_paused: Whether the data integration is paused. Default: `false`.
        :param pulumi.Input[_builtins.str] type: The type of data integration (e.g., 'cloudwatch', etc.).
        :param pulumi.Input[_builtins.str] updated_at: The last update timestamp of the data integration configuration.
        :param pulumi.Input[_builtins.str] updated_by: The user who last updated the data integration configuration.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DataintegrationState.__new__(_DataintegrationState)

        __props__.__dict__["cluster"] = cluster
        __props__.__dict__["config"] = config
        __props__.__dict__["is_paused"] = is_paused
        __props__.__dict__["type"] = type
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["updated_by"] = updated_by
        return Dataintegration(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The cluster where the data integration runs. If unspecified, it will run in the backend.
        """
        return pulumi.get(self, "cluster")

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[_builtins.str]:
        """
        The JSON configuration for the data integration.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the data integration is paused. Default: `false`.
        """
        return pulumi.get(self, "is_paused")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of data integration (e.g., 'cloudwatch', etc.).
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        The last update timestamp of the data integration configuration.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="updatedBy")
    def updated_by(self) -> pulumi.Output[_builtins.str]:
        """
        The user who last updated the data integration configuration.
        """
        return pulumi.get(self, "updated_by")

