# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('groundcover')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_key(self) -> Optional[str]:
        """
        groundcover API Key. Can also be set via the GROUNDCOVER_API_KEY environment variable.
        """
        return __config__.get('apiKey')

    @_builtins.property
    def api_url(self) -> Optional[str]:
        """
        groundcover API URL. Defaults to the groundcover production URL. Can also be set via the GROUNDCOVER_API_URL environment variable.
        """
        return __config__.get('apiUrl')

    @_builtins.property
    def backend_id(self) -> Optional[str]:
        """
        groundcover Backend ID. Can also be set via the GROUNDCOVER_BACKEND_ID environment variable.
        """
        return __config__.get('backendId')

    @_builtins.property
    def org_name(self) -> Optional[str]:
        """
        groundcover Organization Name. Can also be set via the GROUNDCOVER_ORG_NAME environment variable. Deprecated: Use backend_id instead.
        """
        return __config__.get('orgName')

