# REQUIRED: provider is the name of the provider without the pulumi-prefix e.g. "aws".
provider: groundcover
# The name of the GitHub organization or username the repository lives in. Defaults to 'pulumi'
organization: pulumiverse
# The external template only includes workflows relevant for non-Pulumi managed providers.
template: external-bridged-provider
# The name of the GitHub organisation or username where the upstream terraform provider lives.
upstreamProviderOrg: groundcover-com
# Environment variables for CI workflows (pulled from GitHub secrets)
env:
  GROUNDCOVER_API_KEY: ${{ secrets.GROUNDCOVER_API_KEY }}
  GROUNDCOVER_BACKEND_ID: ${{ secrets.GROUNDCOVER_BACKEND_ID }}
# major version of the current provider - used in make files
# This should always be set by all providers as this is key to go module paths.
major-version: 1
# Enable using the terraform converter for example generation.
pulumiConvert: 0
providerDefaultBranch: main
# Reduce parallelism to avoid rate limiting
goBuildParallelism: 2
# Skip master/release workflow tests on PRs
testMasterAndReleaseWorkflows: false
# Enable nightly test workflow
generate-nightly-test-workflow: true
# Enable registry docs generation
registryDocs: true
# Auto-merge upstream provider upgrades
autoMergeProviderUpgrades: true
# Explicit list of languages to support for SDKs. Java is currently excluded because it doesn't yet work well for non-internal providers.
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
publishRegistry: false
