// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Ingestion Key resource.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var groundcoverApiKey = config.Require("groundcoverApiKey");
    ///     var groundcoverBackendId = config.Require("groundcoverBackendId");
    ///     // Example Ingestion Key
    ///     var example = new Groundcover.Ingestionkey("example", new()
    ///     {
    ///         Type = "ingestion",
    ///         RemoteConfig = true,
    ///         Tags = new[]
    ///         {
    ///             "terraform",
    ///             "example",
    ///             "ingestion",
    ///         },
    ///     });
    /// 
    ///     // Example Ingestion Key with minimal configuration
    ///     var minimal = new Groundcover.Ingestionkey("minimal", new()
    ///     {
    ///         Type = "ingestion",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["ingestionkeyExampleKey"] = example.Key,
    ///         ["ingestionkeyExampleCreationDate"] = example.CreationDate,
    ///         ["ingestionkeyExampleCreatedBy"] = example.CreatedBy,
    ///         ["ingestionkeyMinimalKey"] = minimal.Key,
    ///     };
    /// });
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/ingestionkey:Ingestionkey")]
    public partial class Ingestionkey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The user who created the ingestion key.
        /// </summary>
        [Output("createdBy")]
        public Output<string> CreatedBy { get; private set; } = null!;

        /// <summary>
        /// The creation date of the ingestion key. Deprecated: No longer provided by API v1.84.0+
        /// </summary>
        [Output("creationDate")]
        public Output<string> CreationDate { get; private set; } = null!;

        /// <summary>
        /// The actual key value for ingestion.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The name of the ingestion key.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Indicates if the ingestion key is configured for remote configuration.
        /// </summary>
        [Output("remoteConfig")]
        public Output<bool> RemoteConfig { get; private set; } = null!;

        /// <summary>
        /// Tags associated with the ingestion key.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The type of the ingestion key (e.g., 'ingestion').
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a Ingestionkey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ingestionkey(string name, IngestionkeyArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/ingestionkey:Ingestionkey", name, args ?? new IngestionkeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ingestionkey(string name, Input<string> id, IngestionkeyState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/ingestionkey:Ingestionkey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ingestionkey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ingestionkey Get(string name, Input<string> id, IngestionkeyState? state = null, CustomResourceOptions? options = null)
        {
            return new Ingestionkey(name, id, state, options);
        }
    }

    public sealed class IngestionkeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the ingestion key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Indicates if the ingestion key is configured for remote configuration.
        /// </summary>
        [Input("remoteConfig")]
        public Input<bool>? RemoteConfig { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags associated with the ingestion key.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The type of the ingestion key (e.g., 'ingestion').
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public IngestionkeyArgs()
        {
        }
        public static new IngestionkeyArgs Empty => new IngestionkeyArgs();
    }

    public sealed class IngestionkeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The user who created the ingestion key.
        /// </summary>
        [Input("createdBy")]
        public Input<string>? CreatedBy { get; set; }

        /// <summary>
        /// The creation date of the ingestion key. Deprecated: No longer provided by API v1.84.0+
        /// </summary>
        [Input("creationDate")]
        public Input<string>? CreationDate { get; set; }

        /// <summary>
        /// The actual key value for ingestion.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The name of the ingestion key.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Indicates if the ingestion key is configured for remote configuration.
        /// </summary>
        [Input("remoteConfig")]
        public Input<bool>? RemoteConfig { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags associated with the ingestion key.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The type of the ingestion key (e.g., 'ingestion').
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public IngestionkeyState()
        {
        }
        public static new IngestionkeyState Empty => new IngestionkeyState();
    }
}
