// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Metrics Pipeline resource. Singleton resource that configures metrics relabeling rules applied before aggregation.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Groundcover.Metricspipeline("example", new()
    ///     {
    ///         Rules = new Groundcover.Inputs.MetricspipelineRulesArgs
    ///         {
    ///             Add_label = 
    ///             {
    ///                 { "env", "production" },
    ///                 { "team", "platform" },
    ///             },
    ///             Drop_regex = new[]
    ///             {
    ///                 "go_.*",
    ///             },
    ///             Raw = @"  - action: labelmap
    ///     replacement: ""groundcover_$1""
    /// 
    /// ",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import groundcover:index/metricspipeline:Metricspipeline example any
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/metricspipeline:Metricspipeline")]
    public partial class Metricspipeline : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Relabeling rules to apply to metrics.
        /// </summary>
        [Output("rules")]
        public Output<Outputs.MetricspipelineRules?> Rules { get; private set; } = null!;

        /// <summary>
        /// The last update timestamp of the metrics pipeline configuration.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Metricspipeline resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Metricspipeline(string name, MetricspipelineArgs? args = null, CustomResourceOptions? options = null)
            : base("groundcover:index/metricspipeline:Metricspipeline", name, args ?? new MetricspipelineArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Metricspipeline(string name, Input<string> id, MetricspipelineState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/metricspipeline:Metricspipeline", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Metricspipeline resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Metricspipeline Get(string name, Input<string> id, MetricspipelineState? state = null, CustomResourceOptions? options = null)
        {
            return new Metricspipeline(name, id, state, options);
        }
    }

    public sealed class MetricspipelineArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Relabeling rules to apply to metrics.
        /// </summary>
        [Input("rules")]
        public Input<Inputs.MetricspipelineRulesArgs>? Rules { get; set; }

        public MetricspipelineArgs()
        {
        }
        public static new MetricspipelineArgs Empty => new MetricspipelineArgs();
    }

    public sealed class MetricspipelineState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Relabeling rules to apply to metrics.
        /// </summary>
        [Input("rules")]
        public Input<Inputs.MetricspipelineRulesGetArgs>? Rules { get; set; }

        /// <summary>
        /// The last update timestamp of the metrics pipeline configuration.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public MetricspipelineState()
        {
        }
        public static new MetricspipelineState Empty => new MetricspipelineState();
    }
}
