// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// groundcover Monitor resource managed via raw YAML.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var groundcoverApiKey = config.Require("groundcoverApiKey");
    ///     var groundcoverBackendId = config.Require("groundcoverBackendId");
    ///     // Example Monitor: K8s Pod Crash Looping using monitor_yaml
    ///     var k8sPodCrashLooping = new Groundcover.Monitor("k8sPodCrashLooping", new()
    ///     {
    ///         MonitorYaml = @"title: K8s Pod Crash Looping
    /// display:
    ///   header: K8s Pod Crash Looping
    ///   resourceHeaderLabels:
    ///   - workload
    ///   contextHeaderLabels:
    ///   - cluster
    ///   - namespace
    ///   - workload
    ///   description: Kubernetes pod is on a CrashLoopBackOff for more than 5 minutes
    /// severity: S2
    /// measurementType: event
    /// model:
    ///   queries:
    ///   - dataType: metrics
    ///     name: threshold_input_query
    ///     pipeline:
    ///       function:
    ///         name: avg_over_time
    ///         pipelines:
    ///         - function:
    ///             name: avg_by
    ///             pipelines:
    ///             - metric: groundcover_kube_pod_container_status_waiting_reason
    ///             args:
    ///             - cluster
    ///             - namespace
    ///             - workload
    ///         args:
    ///         - 5m
    ///     conditions:
    ///     - key: reason
    ///       origin: root
    ///       type: string
    ///       filters:
    ///       - op: match
    ///         value: CrashLoopBackOff
    ///   thresholds:
    ///   - name: threshold_1
    ///     inputName: threshold_input_query
    ///     operator: gt
    ///     values:
    ///     - 0
    /// executionErrorState: OK
    /// evaluationInterval:
    ///   interval: 1m0s
    ///   pendingFor: 5m0s
    /// ",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["monitorExampleId"] = k8sPodCrashLooping.Id,
    ///         ["monitorExampleYamlOutput"] = k8sPodCrashLooping.MonitorYaml,
    ///     };
    /// });
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/monitor:Monitor")]
    public partial class Monitor : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The monitor definition in YAML format.
        /// </summary>
        [Output("monitorYaml")]
        public Output<string> MonitorYaml { get; private set; } = null!;


        /// <summary>
        /// Create a Monitor resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Monitor(string name, MonitorArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/monitor:Monitor", name, args ?? new MonitorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Monitor(string name, Input<string> id, MonitorState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/monitor:Monitor", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Monitor resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Monitor Get(string name, Input<string> id, MonitorState? state = null, CustomResourceOptions? options = null)
        {
            return new Monitor(name, id, state, options);
        }
    }

    public sealed class MonitorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The monitor definition in YAML format.
        /// </summary>
        [Input("monitorYaml", required: true)]
        public Input<string> MonitorYaml { get; set; } = null!;

        public MonitorArgs()
        {
        }
        public static new MonitorArgs Empty => new MonitorArgs();
    }

    public sealed class MonitorState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The monitor definition in YAML format.
        /// </summary>
        [Input("monitorYaml")]
        public Input<string>? MonitorYaml { get; set; }

        public MonitorState()
        {
        }
        public static new MonitorState Empty => new MonitorState();
    }
}
