// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Manages a groundcover Recurring Silence.
    /// 
    /// Recurring silences allow you to automatically suppress alerts on a repeating schedule based on matching criteria. This is useful for planned maintenance windows, recurring deployments, or other predictable situations where you want to regularly mute alerts.
    /// 
    /// A recurring silence is defined by: a recurrence schedule (daily, weekly, or monthly), a time window (start_time, end_time) in a specific timezone, an optional comment, and one or more matchers that define which alerts to silence.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var groundcoverApiKey = config.Require("groundcoverApiKey");
    ///     var groundcoverBackendId = config.Require("groundcoverBackendId");
    ///     // Example 1: Daily recurring silence for nightly maintenance
    ///     // Silences alerts every day from 2 AM to 4 AM UTC
    ///     var nightlyMaintenance = new Groundcover.RecurringSilence("nightlyMaintenance", new()
    ///     {
    ///         Comment = "Nightly maintenance window for payment-service",
    ///         RecurrenceType = "daily",
    ///         StartTime = "02:00",
    ///         EndTime = "04:00",
    ///         Timezone = "UTC",
    ///         Matchers = new[]
    ///         {
    ///             new Groundcover.Inputs.RecurringSilenceMatcherArgs
    ///             {
    ///                 Name = "service",
    ///                 Value = "payment-service",
    ///                 Is_equal = true,
    ///                 Is_contains = false,
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example 2: Weekly recurring silence for deployment windows
    ///     // Silences alerts every Monday and Wednesday from 9 AM to 11 AM Eastern
    ///     var deploymentWindow = new Groundcover.RecurringSilence("deploymentWindow", new()
    ///     {
    ///         Comment = "Scheduled deployment window",
    ///         RecurrenceType = "weekly",
    ///         StartTime = "09:00",
    ///         EndTime = "11:00",
    ///         Timezone = "America/New_York",
    ///         DaysOfWeeks = new[]
    ///         {
    ///             1,
    ///             3,
    ///         },
    ///         Matchers = new[]
    ///         {
    ///             new Groundcover.Inputs.RecurringSilenceMatcherArgs
    ///             {
    ///                 Name = "workload",
    ///                 Value = "api-gateway",
    ///                 Is_equal = true,
    ///                 Is_contains = false,
    ///             },
    ///             new Groundcover.Inputs.RecurringSilenceMatcherArgs
    ///             {
    ///                 Name = "environment",
    ///                 Value = "staging",
    ///                 Is_equal = true,
    ///                 Is_contains = false,
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example 3: Monthly recurring silence with contains pattern
    ///     // Silences alerts on the 1st and 15th of each month from 10 PM to 6 AM (overnight)
    ///     var patchDay = new Groundcover.RecurringSilence("patchDay", new()
    ///     {
    ///         Comment = "Monthly patch day - overnight maintenance",
    ///         RecurrenceType = "monthly",
    ///         StartTime = "22:00",
    ///         EndTime = "06:00",
    ///         Timezone = "Europe/London",
    ///         DaysOfMonths = new[]
    ///         {
    ///             1,
    ///             15,
    ///         },
    ///         Matchers = new[]
    ///         {
    ///             new Groundcover.Inputs.RecurringSilenceMatcherArgs
    ///             {
    ///                 Name = "service",
    ///                 Value = "app-dev",
    ///                 Is_equal = true,
    ///                 Is_contains = true,
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example 4: Disabled recurring silence with negation (is_equal = false)
    ///     // Silences all alerts EXCEPT for production environment
    ///     var weekendSilence = new Groundcover.RecurringSilence("weekendSilence", new()
    ///     {
    ///         Comment = "Weekend silence - currently disabled",
    ///         RecurrenceType = "weekly",
    ///         StartTime = "00:00",
    ///         EndTime = "23:59",
    ///         Timezone = "UTC",
    ///         DaysOfWeeks = new[]
    ///         {
    ///             0,
    ///             6,
    ///         },
    ///         Enabled = false,
    ///         Matchers = new[]
    ///         {
    ///             new Groundcover.Inputs.RecurringSilenceMatcherArgs
    ///             {
    ///                 Name = "environment",
    ///                 Value = "production",
    ///                 Is_equal = false,
    ///                 Is_contains = false,
    ///             },
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["nightlyMaintenanceId"] = nightlyMaintenance.Id,
    ///         ["deploymentWindowId"] = deploymentWindow.Id,
    ///     };
    /// });
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/recurringSilence:RecurringSilence")]
    public partial class RecurringSilence : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A comment describing the reason for the recurring silence.
        /// </summary>
        [Output("comment")]
        public Output<string> Comment { get; private set; } = null!;

        /// <summary>
        /// Days of the month when the silence should be active (1-31). Required when `RecurrenceType` is `Monthly`.
        /// </summary>
        [Output("daysOfMonths")]
        public Output<ImmutableArray<int>> DaysOfMonths { get; private set; } = null!;

        /// <summary>
        /// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `RecurrenceType` is `Weekly`.
        /// </summary>
        [Output("daysOfWeeks")]
        public Output<ImmutableArray<int>> DaysOfWeeks { get; private set; } = null!;

        /// <summary>
        /// Whether the recurring silence is enabled. Defaults to `True`.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before StartTime to indicate an overnight window (e.g., `22:00` to `06:00`).
        /// </summary>
        [Output("endTime")]
        public Output<string> EndTime { get; private set; } = null!;

        /// <summary>
        /// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
        /// </summary>
        [Output("matchers")]
        public Output<ImmutableArray<Outputs.RecurringSilenceMatcher>> Matchers { get; private set; } = null!;

        /// <summary>
        /// The recurrence type. Must be one of: `Daily`, `Weekly`, `Monthly`.
        /// </summary>
        [Output("recurrenceType")]
        public Output<string> RecurrenceType { get; private set; } = null!;

        /// <summary>
        /// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
        /// </summary>
        [Output("startTime")]
        public Output<string> StartTime { get; private set; } = null!;

        /// <summary>
        /// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
        /// </summary>
        [Output("timezone")]
        public Output<string> Timezone { get; private set; } = null!;


        /// <summary>
        /// Create a RecurringSilence resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RecurringSilence(string name, RecurringSilenceArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/recurringSilence:RecurringSilence", name, args ?? new RecurringSilenceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RecurringSilence(string name, Input<string> id, RecurringSilenceState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/recurringSilence:RecurringSilence", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RecurringSilence resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RecurringSilence Get(string name, Input<string> id, RecurringSilenceState? state = null, CustomResourceOptions? options = null)
        {
            return new RecurringSilence(name, id, state, options);
        }
    }

    public sealed class RecurringSilenceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A comment describing the reason for the recurring silence.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        [Input("daysOfMonths")]
        private InputList<int>? _daysOfMonths;

        /// <summary>
        /// Days of the month when the silence should be active (1-31). Required when `RecurrenceType` is `Monthly`.
        /// </summary>
        public InputList<int> DaysOfMonths
        {
            get => _daysOfMonths ?? (_daysOfMonths = new InputList<int>());
            set => _daysOfMonths = value;
        }

        [Input("daysOfWeeks")]
        private InputList<int>? _daysOfWeeks;

        /// <summary>
        /// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `RecurrenceType` is `Weekly`.
        /// </summary>
        public InputList<int> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<int>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// Whether the recurring silence is enabled. Defaults to `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before StartTime to indicate an overnight window (e.g., `22:00` to `06:00`).
        /// </summary>
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        [Input("matchers", required: true)]
        private InputList<Inputs.RecurringSilenceMatcherArgs>? _matchers;

        /// <summary>
        /// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
        /// </summary>
        public InputList<Inputs.RecurringSilenceMatcherArgs> Matchers
        {
            get => _matchers ?? (_matchers = new InputList<Inputs.RecurringSilenceMatcherArgs>());
            set => _matchers = value;
        }

        /// <summary>
        /// The recurrence type. Must be one of: `Daily`, `Weekly`, `Monthly`.
        /// </summary>
        [Input("recurrenceType", required: true)]
        public Input<string> RecurrenceType { get; set; } = null!;

        /// <summary>
        /// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
        /// </summary>
        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        /// <summary>
        /// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
        /// </summary>
        [Input("timezone", required: true)]
        public Input<string> Timezone { get; set; } = null!;

        public RecurringSilenceArgs()
        {
        }
        public static new RecurringSilenceArgs Empty => new RecurringSilenceArgs();
    }

    public sealed class RecurringSilenceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A comment describing the reason for the recurring silence.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        [Input("daysOfMonths")]
        private InputList<int>? _daysOfMonths;

        /// <summary>
        /// Days of the month when the silence should be active (1-31). Required when `RecurrenceType` is `Monthly`.
        /// </summary>
        public InputList<int> DaysOfMonths
        {
            get => _daysOfMonths ?? (_daysOfMonths = new InputList<int>());
            set => _daysOfMonths = value;
        }

        [Input("daysOfWeeks")]
        private InputList<int>? _daysOfWeeks;

        /// <summary>
        /// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `RecurrenceType` is `Weekly`.
        /// </summary>
        public InputList<int> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<int>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// Whether the recurring silence is enabled. Defaults to `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before StartTime to indicate an overnight window (e.g., `22:00` to `06:00`).
        /// </summary>
        [Input("endTime")]
        public Input<string>? EndTime { get; set; }

        [Input("matchers")]
        private InputList<Inputs.RecurringSilenceMatcherGetArgs>? _matchers;

        /// <summary>
        /// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
        /// </summary>
        public InputList<Inputs.RecurringSilenceMatcherGetArgs> Matchers
        {
            get => _matchers ?? (_matchers = new InputList<Inputs.RecurringSilenceMatcherGetArgs>());
            set => _matchers = value;
        }

        /// <summary>
        /// The recurrence type. Must be one of: `Daily`, `Weekly`, `Monthly`.
        /// </summary>
        [Input("recurrenceType")]
        public Input<string>? RecurrenceType { get; set; }

        /// <summary>
        /// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
        /// </summary>
        [Input("startTime")]
        public Input<string>? StartTime { get; set; }

        /// <summary>
        /// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public RecurringSilenceState()
        {
        }
        public static new RecurringSilenceState Empty => new RecurringSilenceState();
    }
}
