// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Manages a groundcover Synthetic Test. Synthetic tests allow you to proactively monitor your services by running periodic HTTP checks against specified endpoints.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Example: Simple HTTP health check
    ///     var httpHealthCheck = new Groundcover.SyntheticTest("httpHealthCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://httpbin.org/status/200" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "responseTime",
    ///                 Operator = "lt",
    ///                 Target = "5000",
    ///             },
    ///         },
    ///         Retry = new[]
    ///         {
    ///             
    ///             {
    ///                 { "count", 2 },
    ///                 { "interval", "1s" },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: HTTP POST with body and headers
    ///     var httpPostCheck = new Groundcover.SyntheticTest("httpPostCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://httpbin.org/post" },
    ///                 { "method", "POST" },
    ///                 { "timeout", "10s" },
    ///                 { "headers", 
    ///                 {
    ///                     { "Content-Type", "application/json" },
    ///                 } },
    ///                 { "body", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "type", "json" },
    ///                         { "content", "{\"test\": \"data\"}" },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: Authenticated HTTP check using secrets
    ///     var authenticatedCheck = new Groundcover.SyntheticTest("authenticatedCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/health" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///                 { "auth", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "type", "bearer" },
    ///                         { "token", "secretRef::store::your-secret-id" },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: With custom labels and severity
    ///     var performanceCheck = new Groundcover.SyntheticTest("performanceCheck", new()
    ///     {
    ///         Interval = "30s",
    ///         Labels = 
    ///         {
    ///             { "env", "production" },
    ///             { "team", "platform" },
    ///         },
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/status" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "5s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///                 Severity = "critical",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "responseTime",
    ///                 Operator = "lt",
    ///                 Target = "300",
    ///                 Severity = "degraded",
    ///             },
    ///         },
    ///         Retry = new[]
    ///         {
    ///             
    ///             {
    ///                 { "count", 3 },
    ///                 { "interval", "500ms" },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: With monitor and notification routing
    ///     var monitoredCheck = new Groundcover.SyntheticTest("monitoredCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/health" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///         Monitor = new[]
    ///         {
    ///             
    ///             {
    ///                 { "monitorName", "API Health Monitor" },
    ///                 { "severity", "S1" },
    ///                 { "issueSummary", "Synthetic check failed: {{ name }}" },
    ///                 { "issueDescription", "The synthetic test {{ name }} is failing. Check the endpoint health." },
    ///                 { "noDataState", "Alerting" },
    ///                 { "executionErrorState", "Alerting" },
    ///                 { "renotificationInterval", "1h" },
    ///                 { "evaluationInterval", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "interval", "1m" },
    ///                         { "pendingFor", "0s" },
    ///                     },
    ///                 } },
    ///                 { "enabledWorkflows", new[]
    ///                 {
    ///                     "workflow-id-1",
    ///                     "workflow-id-2",
    ///                 } },
    ///             },
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["httpHealthCheckId"] = httpHealthCheck.Id,
    ///         ["httpPostCheckId"] = httpPostCheck.Id,
    ///         ["monitoredCheckId"] = monitoredCheck.Id,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import groundcover:index/syntheticTest:SyntheticTest example "&lt;id&gt;"
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/syntheticTest:SyntheticTest")]
    public partial class SyntheticTest : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        [Output("assertions")]
        public Output<ImmutableArray<Outputs.SyntheticTestAssertion>> Assertions { get; private set; } = null!;

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Output("httpCheck")]
        public Output<Outputs.SyntheticTestHttpCheck?> HttpCheck { get; private set; } = null!;

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Output("interval")]
        public Output<string> Interval { get; private set; } = null!;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Output("monitor")]
        public Output<Outputs.SyntheticTestMonitor?> Monitor { get; private set; } = null!;

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Output("retry")]
        public Output<Outputs.SyntheticTestRetry?> Retry { get; private set; } = null!;

        /// <summary>
        /// Configuration schema version. Managed by the provider.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a SyntheticTest resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SyntheticTest(string name, SyntheticTestArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/syntheticTest:SyntheticTest", name, args ?? new SyntheticTestArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SyntheticTest(string name, Input<string> id, SyntheticTestState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/syntheticTest:SyntheticTest", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SyntheticTest resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SyntheticTest Get(string name, Input<string> id, SyntheticTestState? state = null, CustomResourceOptions? options = null)
        {
            return new SyntheticTest(name, id, state, options);
        }
    }

    public sealed class SyntheticTestArgs : global::Pulumi.ResourceArgs
    {
        [Input("assertions")]
        private InputList<Inputs.SyntheticTestAssertionArgs>? _assertions;

        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        public InputList<Inputs.SyntheticTestAssertionArgs> Assertions
        {
            get => _assertions ?? (_assertions = new InputList<Inputs.SyntheticTestAssertionArgs>());
            set => _assertions = value;
        }

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Input("httpCheck")]
        public Input<Inputs.SyntheticTestHttpCheckArgs>? HttpCheck { get; set; }

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Input("interval", required: true)]
        public Input<string> Interval { get; set; } = null!;

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Input("monitor")]
        public Input<Inputs.SyntheticTestMonitorArgs>? Monitor { get; set; }

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Input("retry")]
        public Input<Inputs.SyntheticTestRetryArgs>? Retry { get; set; }

        public SyntheticTestArgs()
        {
        }
        public static new SyntheticTestArgs Empty => new SyntheticTestArgs();
    }

    public sealed class SyntheticTestState : global::Pulumi.ResourceArgs
    {
        [Input("assertions")]
        private InputList<Inputs.SyntheticTestAssertionGetArgs>? _assertions;

        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        public InputList<Inputs.SyntheticTestAssertionGetArgs> Assertions
        {
            get => _assertions ?? (_assertions = new InputList<Inputs.SyntheticTestAssertionGetArgs>());
            set => _assertions = value;
        }

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Input("httpCheck")]
        public Input<Inputs.SyntheticTestHttpCheckGetArgs>? HttpCheck { get; set; }

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Input("monitor")]
        public Input<Inputs.SyntheticTestMonitorGetArgs>? Monitor { get; set; }

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Input("retry")]
        public Input<Inputs.SyntheticTestRetryGetArgs>? Retry { get; set; }

        /// <summary>
        /// Configuration schema version. Managed by the provider.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public SyntheticTestState()
        {
        }
        public static new SyntheticTestState Empty => new SyntheticTestState();
    }
}
