// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Manages a groundcover Synthetic Test. Synthetic tests allow you to proactively monitor your services by running periodic HTTP, SSL/TLS, TCP, or DNS checks against specified endpoints.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Example: Simple HTTP health check
    ///     var httpHealthCheck = new Groundcover.SyntheticTest("httpHealthCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://httpbin.org/status/200" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "responseTime",
    ///                 Operator = "lt",
    ///                 Target = "5000",
    ///             },
    ///         },
    ///         Retry = new[]
    ///         {
    ///             
    ///             {
    ///                 { "count", 2 },
    ///                 { "interval", "1s" },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: HTTP check with follow_redirects and allow_insecure
    ///     var httpInsecureCheck = new Groundcover.SyntheticTest("httpInsecureCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://httpbin.org/redirect/1" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///                 { "followRedirects", true },
    ///                 { "allowInsecure", true },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: HTTP POST with body and headers
    ///     var httpPostCheck = new Groundcover.SyntheticTest("httpPostCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://httpbin.org/post" },
    ///                 { "method", "POST" },
    ///                 { "timeout", "10s" },
    ///                 { "headers", 
    ///                 {
    ///                     { "Content-Type", "application/json" },
    ///                 } },
    ///                 { "body", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "type", "json" },
    ///                         { "content", "{\"test\": \"data\"}" },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: Authenticated HTTP check using secrets
    ///     var authenticatedCheck = new Groundcover.SyntheticTest("authenticatedCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/health" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///                 { "auth", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "type", "bearer" },
    ///                         { "token", "secretRef::store::your-secret-id" },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: With custom labels and severity
    ///     var performanceCheck = new Groundcover.SyntheticTest("performanceCheck", new()
    ///     {
    ///         Interval = "30s",
    ///         Labels = 
    ///         {
    ///             { "env", "production" },
    ///             { "team", "platform" },
    ///         },
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/status" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "5s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///                 Severity = "critical",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "responseTime",
    ///                 Operator = "lt",
    ///                 Target = "300",
    ///                 Severity = "degraded",
    ///             },
    ///         },
    ///         Retry = new[]
    ///         {
    ///             
    ///             {
    ///                 { "count", 3 },
    ///                 { "interval", "500ms" },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: With monitor and notification routing
    ///     var monitoredCheck = new Groundcover.SyntheticTest("monitoredCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/health" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///         Monitor = new[]
    ///         {
    ///             
    ///             {
    ///                 { "monitorName", "API Health Monitor" },
    ///                 { "severity", "S1" },
    ///                 { "issueSummary", "Synthetic check failed: {{ name }}" },
    ///                 { "issueDescription", "The synthetic test {{ name }} is failing. Check the endpoint health." },
    ///                 { "noDataState", "Alerting" },
    ///                 { "executionErrorState", "Alerting" },
    ///                 { "renotificationInterval", "1h" },
    ///                 { "evaluationInterval", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "interval", "1m" },
    ///                         { "pendingFor", "0s" },
    ///                     },
    ///                 } },
    ///                 { "enabledWorkflows", new[]
    ///                 {
    ///                     "workflow-id-1",
    ///                     "workflow-id-2",
    ///                 } },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: With connected apps notification routing
    ///     var connectedAppsCheck = new Groundcover.SyntheticTest("connectedAppsCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         HttpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "url", "https://api.example.com/health" },
    ///                 { "method", "GET" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "statusCode",
    ///                 Operator = "eq",
    ///                 Target = "200",
    ///             },
    ///         },
    ///         Monitor = new[]
    ///         {
    ///             
    ///             {
    ///                 { "severity", "S2" },
    ///                 { "notificationMethod", "connectedApps" },
    ///                 { "connectedApps", new[]
    ///                 {
    ///                     "slack-app-id",
    ///                     "pagerduty-app-id",
    ///                 } },
    ///                 { "statusFilters", new[]
    ///                 {
    ///                     "Alerting",
    ///                     "Resolved",
    ///                 } },
    ///                 { "disableRenotification", true },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: SSL certificate check with property assertions
    ///     var sslCheck = new Groundcover.SyntheticTest("sslCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         SslCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "host", "example.com" },
    ///                 { "port", 443 },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "ssl",
    ///                 Property = "certificateValid",
    ///                 Operator = "eq",
    ///                 Target = "true",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "ssl",
    ///                 Property = "certificateExpiresIn",
    ///                 Operator = "gt",
    ///                 Target = "30",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: SSL check with TLS version requirement
    ///     var sslTlsCheck = new Groundcover.SyntheticTest("sslTlsCheck", new()
    ///     {
    ///         Interval = "10m",
    ///         SslCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "host", "api.example.com" },
    ///                 { "port", 443 },
    ///                 { "verify", true },
    ///                 { "minVersion", "1.2" },
    ///                 { "sni", "api.example.com" },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "ssl",
    ///                 Property = "certificateValid",
    ///                 Operator = "eq",
    ///                 Target = "true",
    ///             },
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "ssl",
    ///                 Property = "chainValid",
    ///                 Operator = "eq",
    ///                 Target = "true",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: Basic TCP port check
    ///     var tcpCheck = new Groundcover.SyntheticTest("tcpCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         TcpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "host", "example.com" },
    ///                 { "port", 5432 },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "tcp",
    ///                 Operator = "exists",
    ///                 Target = "true",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: TCP check with send/receive
    ///     var tcpSendCheck = new Groundcover.SyntheticTest("tcpSendCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         TcpCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "host", "example.com" },
    ///                 { "port", 6379 },
    ///                 { "send", "PING" },
    ///                 { "expectResponse", true },
    ///                 { "receiveMaxBytes", 1024 },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "tcp",
    ///                 Operator = "exists",
    ///                 Target = "true",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: Basic DNS resolution check
    ///     var dnsCheck = new Groundcover.SyntheticTest("dnsCheck", new()
    ///     {
    ///         Interval = "1m",
    ///         DnsCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "domain", "example.com" },
    ///                 { "recordType", "A" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "dns",
    ///                 Operator = "exists",
    ///                 Target = "true",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: DNS check with custom resolver and DNSSEC
    ///     var dnsFullCheck = new Groundcover.SyntheticTest("dnsFullCheck", new()
    ///     {
    ///         Interval = "5m",
    ///         DnsCheck = new[]
    ///         {
    ///             
    ///             {
    ///                 { "domain", "example.com" },
    ///                 { "recordType", "A" },
    ///                 { "port", 53 },
    ///                 { "resolver", "8.8.8.8" },
    ///                 { "dnssec", true },
    ///                 { "timeout", "10s" },
    ///             },
    ///         },
    ///         Assertions = new[]
    ///         {
    ///             new Groundcover.Inputs.SyntheticTestAssertionArgs
    ///             {
    ///                 Source = "dns",
    ///                 Operator = "exists",
    ///                 Target = "true",
    ///             },
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["httpHealthCheckId"] = httpHealthCheck.Id,
    ///         ["httpPostCheckId"] = httpPostCheck.Id,
    ///         ["monitoredCheckId"] = monitoredCheck.Id,
    ///         ["sslCheckId"] = sslCheck.Id,
    ///         ["tcpCheckId"] = tcpCheck.Id,
    ///         ["dnsCheckId"] = dnsCheck.Id,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Assertion Property Reference
    /// 
    /// The `Property` field in an assertion specifies which property to evaluate within the assertion source. Its usage varies by source:
    /// 
    /// ### `responseHeader`
    /// 
    /// Set `Property` to the header name (case-insensitive).
    /// 
    /// Supported operators: `Exists`, `notExists`, `Eq`, `Ne`, `Contains`.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    /// });
    /// ```
    /// 
    /// ### `jsonBody`
    /// 
    /// Set `Property` to a dot-notation path into the JSON response body (e.g. `user.name`, `data.items`).
    /// 
    /// Supported operators: `Exists`, `notExists`, `Eq`, `Ne`, `Contains`.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    /// });
    /// ```
    /// 
    /// ### `responseBody`
    /// 
    /// Asserts against the entire raw response body as plain text. The `Property` field is not used for this source and should be omitted.
    /// 
    /// Supported operators: `Eq`, `Ne`, `Contains`, `Exists`, `notExists`.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    /// });
    /// ```
    /// 
    /// ### `Ssl`
    /// 
    /// Set `Property` to one of the following:
    /// 
    /// | Property | Description | Operators | Target example |
    /// |---|---|---|---|
    /// | `certificateValid` | Whether the certificate is valid | `Eq` | `True` / `False` |
    /// | `certificateExpiresIn` | Days until certificate expiry | `Gt`, `Lt` | `30` |
    /// | `tlsVersion` | Negotiated TLS version | `Eq`, `Gt`, `Lt` | `1.2` |
    /// | `chainValid` | Whether the certificate chain is valid | `Eq` | `True` / `False` |
    /// | `cipherSuite` | Negotiated cipher suite | `Eq`, `Contains` | `AES256` |
    /// 
    /// ### `Tcp`
    /// 
    /// The `Property` field is optional for TCP assertions. When omitted, operators act as connection checks by default.
    /// 
    /// | Property | Description | Operators |
    /// |---|---|---|
    /// | `Connection` | Connection check (explicit) | `Exists`, `notExists`, `Eq`, `Ne` |
    /// | `responseContains` | Match response body content | `Contains` |
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import groundcover:index/syntheticTest:SyntheticTest example "&lt;id&gt;"
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/syntheticTest:SyntheticTest")]
    public partial class SyntheticTest : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        [Output("assertions")]
        public Output<ImmutableArray<Outputs.SyntheticTestAssertion>> Assertions { get; private set; } = null!;

        /// <summary>
        /// DNS check configuration. Tests DNS resolution and optionally validates DNSSEC.
        /// </summary>
        [Output("dnsCheck")]
        public Output<Outputs.SyntheticTestDnsCheck?> DnsCheck { get; private set; } = null!;

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Output("httpCheck")]
        public Output<Outputs.SyntheticTestHttpCheck?> HttpCheck { get; private set; } = null!;

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Output("interval")]
        public Output<string> Interval { get; private set; } = null!;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Output("monitor")]
        public Output<Outputs.SyntheticTestMonitor?> Monitor { get; private set; } = null!;

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Output("retry")]
        public Output<Outputs.SyntheticTestRetry?> Retry { get; private set; } = null!;

        /// <summary>
        /// SSL/TLS check configuration. Validates SSL certificates and TLS connections.
        /// </summary>
        [Output("sslCheck")]
        public Output<Outputs.SyntheticTestSslCheck?> SslCheck { get; private set; } = null!;

        /// <summary>
        /// TCP check configuration. Tests TCP connectivity and optionally sends/receives data.
        /// </summary>
        [Output("tcpCheck")]
        public Output<Outputs.SyntheticTestTcpCheck?> TcpCheck { get; private set; } = null!;

        /// <summary>
        /// Configuration schema version. Managed by the provider.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a SyntheticTest resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SyntheticTest(string name, SyntheticTestArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/syntheticTest:SyntheticTest", name, args ?? new SyntheticTestArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SyntheticTest(string name, Input<string> id, SyntheticTestState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/syntheticTest:SyntheticTest", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SyntheticTest resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SyntheticTest Get(string name, Input<string> id, SyntheticTestState? state = null, CustomResourceOptions? options = null)
        {
            return new SyntheticTest(name, id, state, options);
        }
    }

    public sealed class SyntheticTestArgs : global::Pulumi.ResourceArgs
    {
        [Input("assertions")]
        private InputList<Inputs.SyntheticTestAssertionArgs>? _assertions;

        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        public InputList<Inputs.SyntheticTestAssertionArgs> Assertions
        {
            get => _assertions ?? (_assertions = new InputList<Inputs.SyntheticTestAssertionArgs>());
            set => _assertions = value;
        }

        /// <summary>
        /// DNS check configuration. Tests DNS resolution and optionally validates DNSSEC.
        /// </summary>
        [Input("dnsCheck")]
        public Input<Inputs.SyntheticTestDnsCheckArgs>? DnsCheck { get; set; }

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Input("httpCheck")]
        public Input<Inputs.SyntheticTestHttpCheckArgs>? HttpCheck { get; set; }

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Input("interval", required: true)]
        public Input<string> Interval { get; set; } = null!;

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Input("monitor")]
        public Input<Inputs.SyntheticTestMonitorArgs>? Monitor { get; set; }

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Input("retry")]
        public Input<Inputs.SyntheticTestRetryArgs>? Retry { get; set; }

        /// <summary>
        /// SSL/TLS check configuration. Validates SSL certificates and TLS connections.
        /// </summary>
        [Input("sslCheck")]
        public Input<Inputs.SyntheticTestSslCheckArgs>? SslCheck { get; set; }

        /// <summary>
        /// TCP check configuration. Tests TCP connectivity and optionally sends/receives data.
        /// </summary>
        [Input("tcpCheck")]
        public Input<Inputs.SyntheticTestTcpCheckArgs>? TcpCheck { get; set; }

        public SyntheticTestArgs()
        {
        }
        public static new SyntheticTestArgs Empty => new SyntheticTestArgs();
    }

    public sealed class SyntheticTestState : global::Pulumi.ResourceArgs
    {
        [Input("assertions")]
        private InputList<Inputs.SyntheticTestAssertionGetArgs>? _assertions;

        /// <summary>
        /// Assertions to validate the check result.
        /// </summary>
        public InputList<Inputs.SyntheticTestAssertionGetArgs> Assertions
        {
            get => _assertions ?? (_assertions = new InputList<Inputs.SyntheticTestAssertionGetArgs>());
            set => _assertions = value;
        }

        /// <summary>
        /// DNS check configuration. Tests DNS resolution and optionally validates DNSSEC.
        /// </summary>
        [Input("dnsCheck")]
        public Input<Inputs.SyntheticTestDnsCheckGetArgs>? DnsCheck { get; set; }

        /// <summary>
        /// Whether the synthetic test is enabled. Default: `True`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// HTTP check configuration. Defines the endpoint to monitor.
        /// </summary>
        [Input("httpCheck")]
        public Input<Inputs.SyntheticTestHttpCheckGetArgs>? HttpCheck { get; set; }

        /// <summary>
        /// How often the check runs. Supported values: `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Extra labels to attach to the synthetic test metrics.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Monitor configuration for the synthetic test. Controls the monitor that is automatically created for this test, including alerting behavior and notification routing.
        /// </summary>
        [Input("monitor")]
        public Input<Inputs.SyntheticTestMonitorGetArgs>? Monitor { get; set; }

        /// <summary>
        /// The name of the synthetic test.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Retry policy for failed checks.
        /// </summary>
        [Input("retry")]
        public Input<Inputs.SyntheticTestRetryGetArgs>? Retry { get; set; }

        /// <summary>
        /// SSL/TLS check configuration. Validates SSL certificates and TLS connections.
        /// </summary>
        [Input("sslCheck")]
        public Input<Inputs.SyntheticTestSslCheckGetArgs>? SslCheck { get; set; }

        /// <summary>
        /// TCP check configuration. Tests TCP connectivity and optionally sends/receives data.
        /// </summary>
        [Input("tcpCheck")]
        public Input<Inputs.SyntheticTestTcpCheckGetArgs>? TcpCheck { get; set; }

        /// <summary>
        /// Configuration schema version. Managed by the provider.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public SyntheticTestState()
        {
        }
        public static new SyntheticTestState Empty => new SyntheticTestState();
    }
}
