// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover
{
    /// <summary>
    /// Traces Pipeline resource. This is a singleton resource.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Groundcover = GroundcoverCom.Groundcover;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var groundcoverApiKey = config.Require("groundcoverApiKey");
    ///     var groundcoverBackendId = config.Require("groundcoverBackendId");
    ///     // Example Traces Pipeline
    ///     var tracespipeline = new Groundcover.Tracespipeline("tracespipeline", new()
    ///     {
    ///         Value = @"ottlRules:
    ///   - ruleName: example-rule
    ///     conditions:
    ///       - workload == ""nginx""
    ///     statements:
    ///       - set(attributes[""test.key""], ""test-value"")
    /// ",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["tracesPipelineUpdatedAt"] = tracespipeline.UpdatedAt,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Traces pipeline is a singleton resource. The import ID value is ignored.
    /// 
    /// ```sh
    /// $ pulumi import groundcover:index/tracespipeline:Tracespipeline example any
    /// ```
    /// </summary>
    [GroundcoverResourceType("groundcover:index/tracespipeline:Tracespipeline")]
    public partial class Tracespipeline : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The last update timestamp of the traces pipeline configuration.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// The YAML representation of the traces pipeline configuration.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a Tracespipeline resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Tracespipeline(string name, TracespipelineArgs args, CustomResourceOptions? options = null)
            : base("groundcover:index/tracespipeline:Tracespipeline", name, args ?? new TracespipelineArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Tracespipeline(string name, Input<string> id, TracespipelineState? state = null, CustomResourceOptions? options = null)
            : base("groundcover:index/tracespipeline:Tracespipeline", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/groundcover-com/pulumi-groundcover",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Tracespipeline resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Tracespipeline Get(string name, Input<string> id, TracespipelineState? state = null, CustomResourceOptions? options = null)
        {
            return new Tracespipeline(name, id, state, options);
        }
    }

    public sealed class TracespipelineArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The YAML representation of the traces pipeline configuration.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public TracespipelineArgs()
        {
        }
        public static new TracespipelineArgs Empty => new TracespipelineArgs();
    }

    public sealed class TracespipelineState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The last update timestamp of the traces pipeline configuration.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// The YAML representation of the traces pipeline configuration.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public TracespipelineState()
        {
        }
        public static new TracespipelineState Empty => new TracespipelineState();
    }
}
