// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Outputs
{

    [OutputType]
    public sealed class MetricspipelineRules
    {
        /// <summary>
        /// Map of label key-value pairs to add to every metric.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? AddLabel;
        /// <summary>
        /// List of regex patterns. Metrics whose **name** matches any pattern are dropped.
        /// </summary>
        public readonly ImmutableArray<string> DropRegexes;
        /// <summary>
        /// List of regex patterns. Only metrics whose **name** matches at least one pattern are kept. All others are dropped.
        /// </summary>
        public readonly ImmutableArray<string> KeepRegexes;
        /// <summary>
        /// Raw VictoriaMetrics relabeling rules in YAML format for advanced use cases.
        /// </summary>
        public readonly string? Raw;
        /// <summary>
        /// List of label names to remove from every metric. Be careful with this setting as it can cause metrics amalgamation.
        /// </summary>
        public readonly ImmutableArray<string> RemoveLabels;

        [OutputConstructor]
        private MetricspipelineRules(
            ImmutableDictionary<string, string>? addLabel,

            ImmutableArray<string> dropRegexes,

            ImmutableArray<string> keepRegexes,

            string? raw,

            ImmutableArray<string> removeLabels)
        {
            AddLabel = addLabel;
            DropRegexes = dropRegexes;
            KeepRegexes = keepRegexes;
            Raw = raw;
            RemoveLabels = removeLabels;
        }
    }
}
