// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Outputs
{

    [OutputType]
    public sealed class NotificationRouteRoute
    {
        /// <summary>
        /// List of connected apps to notify for this route.
        /// </summary>
        public readonly ImmutableArray<Outputs.NotificationRouteRouteConnectedApp> ConnectedApps;
        /// <summary>
        /// List of issue statuses that trigger this route (e.g., 'Alerting', 'Resolved').
        /// </summary>
        public readonly ImmutableArray<string> Statuses;

        [OutputConstructor]
        private NotificationRouteRoute(
            ImmutableArray<Outputs.NotificationRouteRouteConnectedApp> connectedApps,

            ImmutableArray<string> statuses)
        {
            ConnectedApps = connectedApps;
            Statuses = statuses;
        }
    }
}
