// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Groundcover.Outputs
{

    [OutputType]
    public sealed class PolicyDataScopeAdvancedMetrics
    {
        /// <summary>
        /// List of conditions for the data scope.
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicyDataScopeAdvancedMetricsCondition> Conditions;
        /// <summary>
        /// Whether this data type is disabled (no data access). When true, users have no access to this data type.
        /// </summary>
        public readonly bool? Disabled;
        /// <summary>
        /// Logical operator (e.g., 'and', 'or').
        /// </summary>
        public readonly string Operator;

        [OutputConstructor]
        private PolicyDataScopeAdvancedMetrics(
            ImmutableArray<Outputs.PolicyDataScopeAdvancedMetricsCondition> conditions,

            bool? disabled,

            string @operator)
        {
            Conditions = conditions;
            Disabled = disabled;
            Operator = @operator;
        }
    }
}
