// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Groundcover.Outputs
{

    [OutputType]
    public sealed class PolicyDataScopeSimpleConditionFilter
    {
        /// <summary>
        /// The filter operation (e.g., 'match').
        /// </summary>
        public readonly string Op;
        /// <summary>
        /// The value to filter on.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private PolicyDataScopeSimpleConditionFilter(
            string op,

            string value)
        {
            Op = op;
            Value = value;
        }
    }
}
