// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Outputs
{

    [OutputType]
    public sealed class SyntheticTestAssertion
    {
        /// <summary>
        /// Comparison operator: `Eq`, `Ne`, `Gt`, `Lt`, `Contains`, `Exists`, `notExists`, `startsWith`, `endsWith`, `Regex`, `oneOf`.
        /// </summary>
        public readonly string Operator;
        /// <summary>
        /// Specifies which property to evaluate within the assertion source. Usage varies by source — see documentation for per-source details.
        /// </summary>
        public readonly string? Property;
        /// <summary>
        /// Assertion severity: `Critical` (default) or `Degraded`.
        /// </summary>
        public readonly string? Severity;
        /// <summary>
        /// What to assert on: `statusCode`, `responseTime`, `responseHeader`, `jsonBody`, `responseBody`, `Ssl`, `Tcp`, `Dns`.
        /// </summary>
        public readonly string Source;
        /// <summary>
        /// Expected value to compare against (as string, e.g. `"200"` for status code).
        /// </summary>
        public readonly string? Target;

        [OutputConstructor]
        private SyntheticTestAssertion(
            string @operator,

            string? property,

            string? severity,

            string source,

            string? target)
        {
            Operator = @operator;
            Property = property;
            Severity = severity;
            Source = source;
            Target = target;
        }
    }
}
