// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ApikeyPolicy {
    /**
     * Policy name.
     */
    name: string;
    /**
     * Policy UUID.
     */
    uuid: string;
}

export interface NotificationRouteNotificationSettings {
    /**
     * Duration between renotifications (e.g., '1h', '30m'). The API may normalize this value.
     */
    renotificationInterval?: string;
}

export interface NotificationRouteRoute {
    /**
     * List of connected apps to notify for this route.
     */
    connectedApps: outputs.NotificationRouteRouteConnectedApp[];
    /**
     * List of issue statuses that trigger this route (e.g., 'Alerting', 'Resolved').
     */
    statuses: string[];
}

export interface NotificationRouteRouteConnectedApp {
    /**
     * ID of the connected app.
     */
    id: string;
    /**
     * Type of connected app (e.g., 'slack-webhook', 'pagerduty').
     */
    type: string;
}

export interface PolicyDataScope {
    /**
     * Advanced data scope configuration. Allows per-data-type filtering rules for fine-grained access control.
     */
    advanced?: outputs.PolicyDataScopeAdvanced;
    /**
     * Simple data scope configuration. Applies a single set of filtering rules to all data types.
     */
    simple?: outputs.PolicyDataScopeSimple;
}

export interface PolicyDataScopeAdvanced {
    /**
     * Data scope rules for events.
     */
    events?: outputs.PolicyDataScopeAdvancedEvents;
    /**
     * Data scope rules for logs.
     */
    logs?: outputs.PolicyDataScopeAdvancedLogs;
    /**
     * Data scope rules for metrics.
     */
    metrics?: outputs.PolicyDataScopeAdvancedMetrics;
    /**
     * Data scope rules for traces.
     */
    traces?: outputs.PolicyDataScopeAdvancedTraces;
    /**
     * Data scope rules for workloads.
     */
    workloads?: outputs.PolicyDataScopeAdvancedWorkloads;
}

export interface PolicyDataScopeAdvancedEvents {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeAdvancedEventsCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeAdvancedEventsCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeAdvancedEventsConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeAdvancedEventsConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface PolicyDataScopeAdvancedLogs {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeAdvancedLogsCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeAdvancedLogsCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeAdvancedLogsConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeAdvancedLogsConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface PolicyDataScopeAdvancedMetrics {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeAdvancedMetricsCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeAdvancedMetricsCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeAdvancedMetricsConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeAdvancedMetricsConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface PolicyDataScopeAdvancedTraces {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeAdvancedTracesCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeAdvancedTracesCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeAdvancedTracesConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeAdvancedTracesConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface PolicyDataScopeAdvancedWorkloads {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeAdvancedWorkloadsCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeAdvancedWorkloadsCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeAdvancedWorkloadsConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeAdvancedWorkloadsConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface PolicyDataScopeSimple {
    /**
     * List of conditions for the data scope.
     */
    conditions: outputs.PolicyDataScopeSimpleCondition[];
    /**
     * Whether this data type is disabled (no data access). When true, users have no access to this data type.
     */
    disabled?: boolean;
    /**
     * Logical operator (e.g., 'and', 'or').
     */
    operator: string;
}

export interface PolicyDataScopeSimpleCondition {
    /**
     * List of filter criteria for the condition.
     */
    filters: outputs.PolicyDataScopeSimpleConditionFilter[];
    /**
     * The key for the condition (e.g., 'environment').
     */
    key: string;
    /**
     * The origin of the key.
     */
    origin: string;
    /**
     * The type of the key.
     */
    type: string;
}

export interface PolicyDataScopeSimpleConditionFilter {
    /**
     * The filter operation (e.g., 'match').
     */
    op: string;
    /**
     * The value to filter on.
     */
    value: string;
}

export interface SilenceMatcher {
    /**
     * If true, the value is treated as a contains pattern (partial match). If false, the value must match exactly. Defaults to `false`.
     */
    isContains: boolean;
    /**
     * If true, the matcher will match when the label value equals the specified value. If false, it matches when the value does NOT equal. Defaults to `true`.
     */
    isEqual: boolean;
    /**
     * The name of the label to match (e.g., `service`, `environment`, `workload`).
     */
    name: string;
    /**
     * The value to match against. Can be an exact value or a partial match pattern if `isContains` is true.
     */
    value: string;
}

export interface SyntheticTestAssertion {
    /**
     * Comparison operator: `eq`, `ne`, `gt`, `lt`, `contains`, `exists`, `notExists`, `startsWith`, `endsWith`, `regex`, `oneOf`.
     */
    operator: string;
    /**
     * Specifies which property to evaluate within the assertion source. Usage varies by source — see documentation for per-source details.
     */
    property?: string;
    /**
     * Assertion severity: `critical` (default) or `degraded`.
     */
    severity?: string;
    /**
     * What to assert on: `statusCode`, `responseTime`, `responseHeader`, `jsonBody`, `responseBody`, `ssl`, `tcp`, `dns`.
     */
    source: string;
    /**
     * Expected value to compare against (as string, e.g. `"200"` for status code).
     */
    target?: string;
}

export interface SyntheticTestDnsCheck {
    /**
     * Whether to validate DNSSEC.
     */
    dnssec?: boolean;
    /**
     * (Required) The domain name to resolve.
     */
    domain?: string;
    /**
     * The DNS server port (1-65535). Defaults to 53.
     */
    port?: number;
    /**
     * (Required) DNS record type to query. Supported values: `A`, `AAAA`, `CNAME`, `MX`, `NS`, `TXT`, `SOA`, `SRV`, `PTR`.
     */
    recordType?: string;
    /**
     * Custom DNS resolver address (e.g. `8.8.8.8`).
     */
    resolver?: string;
    /**
     * Timeout for the DNS check (e.g. `5s`, `10s`).
     */
    timeout?: string;
}

export interface SyntheticTestHttpCheck {
    /**
     * Whether to allow insecure TLS connections.
     */
    allowInsecure?: boolean;
    /**
     * HTTP authentication. Supports `basic`, `bearer`, or `none`.
     */
    auth?: outputs.SyntheticTestHttpCheckAuth;
    /**
     * HTTP request body.
     */
    body?: outputs.SyntheticTestHttpCheckBody;
    /**
     * Whether to follow HTTP redirects.
     */
    followRedirects?: boolean;
    /**
     * HTTP headers to send with the request.
     */
    headers?: {[key: string]: string};
    /**
     * (Required) HTTP method. Supported: `GET`, `POST`, `PUT`, `PATCH`, `DELETE`, `HEAD`, `OPTIONS`.
     */
    method?: string;
    /**
     * Request timeout (e.g. `10s`, `30s`).
     */
    timeout: string;
    /**
     * (Required) The URL to check (must include http:// or https://).
     */
    url?: string;
}

export interface SyntheticTestHttpCheckAuth {
    /**
     * Password for basic auth. Supports `secretRef::store::<id>` references.
     */
    password?: string;
    /**
     * Token for bearer auth. Supports `secretRef::store::<id>` references.
     */
    token?: string;
    /**
     * Auth type: `basic`, `bearer`, or `none`.
     */
    type?: string;
    /**
     * Username for basic auth.
     */
    username?: string;
}

export interface SyntheticTestHttpCheckBody {
    /**
     * Body content string.
     */
    content?: string;
    /**
     * Body content type: `json`, `text`, or `raw`.
     */
    type?: string;
}

export interface SyntheticTestMonitor {
    /**
     * List of connected app IDs for direct notification delivery. Required when `notificationMethod` is `connectedApps`.
     */
    connectedApps?: string[];
    /**
     * Disable repeated notifications for the same issue.
     */
    disableRenotification?: boolean;
    /**
     * List of workflow IDs to route notifications to. Workflows and notification policies run simultaneously.
     */
    enabledWorkflows?: string[];
    /**
     * Evaluation interval settings for the monitor.
     */
    evaluationInterval?: outputs.SyntheticTestMonitorEvaluationInterval;
    /**
     * How the monitor behaves on execution errors. `OK` treats errors as normal, `Alerting` treats them as issues.
     */
    executionErrorState?: string;
    /**
     * Description template for issues created by this monitor. Supports Jinja2 templating with variables like `{{ workload }}`.
     */
    issueDescription?: string;
    /**
     * Summary template for issues created by this monitor. Supports Jinja2 templating.
     */
    issueSummary?: string;
    /**
     * The time window the monitor looks back for evaluation (e.g. `5m`, `10m`).
     */
    lookbehindWindow?: string;
    /**
     * Custom name for the monitor. If not set, a default name is derived from the synthetic test name.
     */
    monitorName?: string;
    /**
     * How the monitor behaves when there is no data. `OK` treats no data as normal, `Alerting` treats it as an issue.
     */
    noDataState?: string;
    /**
     * How the synthetic monitor delivers alert notifications. Supported values: `notificationRoutes` (default), `connectedApps`, `noNotifications`.
     */
    notificationMethod?: string;
    /**
     * How long to wait before sending another notification while the alert is still firing (e.g. `15m`, `1h`, `4h`).
     */
    renotificationInterval?: string;
    /**
     * Severity level for issues created by this monitor. Supported values: `S1`, `S2`, `S3`, `S4`, `none`.
     */
    severity?: string;
    /**
     * Which issue statuses trigger notifications. Supported values: `Alerting`, `Resolved`. Only applicable when `notificationMethod` is `connectedApps`.
     */
    statusFilters?: string[];
}

export interface SyntheticTestMonitorEvaluationInterval {
    /**
     * How often the monitor evaluates (e.g. `1m`, `5m`).
     */
    interval?: string;
    /**
     * How long all evaluations must stay true before firing (e.g. `0s`, `1m`, `5m`).
     */
    pendingFor?: string;
}

export interface SyntheticTestRetry {
    /**
     * Number of retry attempts.
     */
    count?: number;
    /**
     * Delay between retries (e.g. `1s`, `500ms`).
     */
    interval?: string;
}

export interface SyntheticTestSslCheck {
    /**
     * (Required) The hostname to connect to for the SSL check.
     */
    host?: string;
    /**
     * Minimum TLS version to accept (e.g. `1.2`, `1.3`).
     */
    minVersion?: string;
    /**
     * (Required) The port to connect to (1-65535).
     */
    port?: number;
    /**
     * Server Name Indication (SNI) value for the TLS handshake. Defaults to the host value.
     */
    sni?: string;
    /**
     * Timeout for the SSL check (e.g. `5s`, `10s`).
     */
    timeout?: string;
    /**
     * Whether to verify the SSL certificate.
     */
    verify?: boolean;
}

export interface SyntheticTestTcpCheck {
    /**
     * Whether to expect a response from the TCP endpoint.
     */
    expectResponse?: boolean;
    /**
     * (Required) The hostname to connect to for the TCP check.
     */
    host?: string;
    /**
     * (Required) The port to connect to (1-65535).
     */
    port?: number;
    /**
     * Maximum number of bytes to receive in the response.
     */
    receiveMaxBytes?: number;
    /**
     * Data to send over the TCP connection.
     */
    send?: string;
    /**
     * Timeout for the TCP check (e.g. `5s`, `10s`).
     */
    timeout?: string;
}

