// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class NotificationRouteRouteArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectedApps", required: true)]
        private InputList<Inputs.NotificationRouteRouteConnectedAppArgs>? _connectedApps;

        /// <summary>
        /// List of connected apps to notify for this route.
        /// </summary>
        public InputList<Inputs.NotificationRouteRouteConnectedAppArgs> ConnectedApps
        {
            get => _connectedApps ?? (_connectedApps = new InputList<Inputs.NotificationRouteRouteConnectedAppArgs>());
            set => _connectedApps = value;
        }

        [Input("statuses", required: true)]
        private InputList<string>? _statuses;

        /// <summary>
        /// List of issue statuses that trigger this route (e.g., 'Alerting', 'Resolved').
        /// </summary>
        public InputList<string> Statuses
        {
            get => _statuses ?? (_statuses = new InputList<string>());
            set => _statuses = value;
        }

        public NotificationRouteRouteArgs()
        {
        }
        public static new NotificationRouteRouteArgs Empty => new NotificationRouteRouteArgs();
    }
}
