// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class NotificationRouteNotificationSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Duration between renotifications (e.g., '1h', '30m'). The API may normalize this value.
        /// </summary>
        [Input("renotificationInterval")]
        public Input<string>? RenotificationInterval { get; set; }

        public NotificationRouteNotificationSettingsArgs()
        {
        }
        public static new NotificationRouteNotificationSettingsArgs Empty => new NotificationRouteNotificationSettingsArgs();
    }
}
