// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Groundcover.Inputs
{

    public sealed class PolicyDataScopeAdvancedEventsConditionFilterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The filter operation (e.g., 'match').
        /// </summary>
        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        /// <summary>
        /// The value to filter on.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public PolicyDataScopeAdvancedEventsConditionFilterArgs()
        {
        }
        public static new PolicyDataScopeAdvancedEventsConditionFilterArgs Empty => new PolicyDataScopeAdvancedEventsConditionFilterArgs();
    }
}
