// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class PolicyDataScopeAdvancedArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Data scope rules for events.
        /// </summary>
        [Input("events")]
        public Input<Inputs.PolicyDataScopeAdvancedEventsArgs>? Events { get; set; }

        /// <summary>
        /// Data scope rules for logs.
        /// </summary>
        [Input("logs")]
        public Input<Inputs.PolicyDataScopeAdvancedLogsArgs>? Logs { get; set; }

        /// <summary>
        /// Data scope rules for metrics.
        /// </summary>
        [Input("metrics")]
        public Input<Inputs.PolicyDataScopeAdvancedMetricsArgs>? Metrics { get; set; }

        /// <summary>
        /// Data scope rules for traces.
        /// </summary>
        [Input("traces")]
        public Input<Inputs.PolicyDataScopeAdvancedTracesArgs>? Traces { get; set; }

        /// <summary>
        /// Data scope rules for workloads.
        /// </summary>
        [Input("workloads")]
        public Input<Inputs.PolicyDataScopeAdvancedWorkloadsArgs>? Workloads { get; set; }

        public PolicyDataScopeAdvancedArgs()
        {
        }
        public static new PolicyDataScopeAdvancedArgs Empty => new PolicyDataScopeAdvancedArgs();
    }
}
