// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class PolicyDataScopeAdvancedWorkloadsConditionArgs : global::Pulumi.ResourceArgs
    {
        [Input("filters", required: true)]
        private InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionFilterArgs>? _filters;

        /// <summary>
        /// List of filter criteria for the condition.
        /// </summary>
        public InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionFilterArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The key for the condition (e.g., 'environment').
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The origin of the key.
        /// </summary>
        [Input("origin", required: true)]
        public Input<string> Origin { get; set; } = null!;

        /// <summary>
        /// The type of the key.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public PolicyDataScopeAdvancedWorkloadsConditionArgs()
        {
        }
        public static new PolicyDataScopeAdvancedWorkloadsConditionArgs Empty => new PolicyDataScopeAdvancedWorkloadsConditionArgs();
    }
}
