// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class PolicyDataScopeAdvancedWorkloadsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions", required: true)]
        private InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionGetArgs>? _conditions;

        /// <summary>
        /// List of conditions for the data scope.
        /// </summary>
        public InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionGetArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.PolicyDataScopeAdvancedWorkloadsConditionGetArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// Whether this data type is disabled (no data access). When true, users have no access to this data type.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// Logical operator (e.g., 'and', 'or').
        /// </summary>
        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        public PolicyDataScopeAdvancedWorkloadsGetArgs()
        {
        }
        public static new PolicyDataScopeAdvancedWorkloadsGetArgs Empty => new PolicyDataScopeAdvancedWorkloadsGetArgs();
    }
}
