// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class SyntheticTestHttpCheckGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to allow insecure TLS connections.
        /// </summary>
        [Input("allowInsecure")]
        public Input<bool>? AllowInsecure { get; set; }

        /// <summary>
        /// HTTP authentication. Supports `Basic`, `Bearer`, or `None`.
        /// </summary>
        [Input("auth")]
        public Input<Inputs.SyntheticTestHttpCheckAuthGetArgs>? Auth { get; set; }

        /// <summary>
        /// HTTP request body.
        /// </summary>
        [Input("body")]
        public Input<Inputs.SyntheticTestHttpCheckBodyGetArgs>? Body { get; set; }

        /// <summary>
        /// Whether to follow HTTP redirects.
        /// </summary>
        [Input("followRedirects")]
        public Input<bool>? FollowRedirects { get; set; }

        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// HTTP headers to send with the request.
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        /// <summary>
        /// (Required) HTTP method. Supported: `GET`, `POST`, `PUT`, `PATCH`, `DELETE`, `HEAD`, `OPTIONS`.
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        /// <summary>
        /// Request timeout (e.g. `10s`, `30s`).
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        /// <summary>
        /// (Required) The URL to check (must include http:// or https://).
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public SyntheticTestHttpCheckGetArgs()
        {
        }
        public static new SyntheticTestHttpCheckGetArgs Empty => new SyntheticTestHttpCheckGetArgs();
    }
}
