// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class SyntheticTestAssertionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Comparison operator: `Eq`, `Ne`, `Gt`, `Lt`, `Contains`, `Exists`, `notExists`, `startsWith`, `endsWith`, `Regex`, `oneOf`.
        /// </summary>
        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        /// <summary>
        /// Property path for header, JSON body, or SSL assertions (e.g. `Content-Type`, `data.id`, `certificateValid`, `certificateExpiresIn`, `tlsVersion`, `chainValid`).
        /// </summary>
        [Input("property")]
        public Input<string>? Property { get; set; }

        /// <summary>
        /// Assertion severity: `Critical` (default) or `Degraded`.
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// What to assert on: `statusCode`, `responseTime`, `responseHeader`, `jsonBody`, `responseBody`, `Ssl`.
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        /// <summary>
        /// Expected value to compare against (as string, e.g. `"200"` for status code).
        /// </summary>
        [Input("target")]
        public Input<string>? Target { get; set; }

        public SyntheticTestAssertionArgs()
        {
        }
        public static new SyntheticTestAssertionArgs Empty => new SyntheticTestAssertionArgs();
    }
}
