// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace GroundcoverCom.Groundcover.Inputs
{

    public sealed class SyntheticTestTcpCheckArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to expect a response from the TCP endpoint.
        /// </summary>
        [Input("expectResponse")]
        public Input<bool>? ExpectResponse { get; set; }

        /// <summary>
        /// (Required) The hostname to connect to for the TCP check.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// (Required) The port to connect to (1-65535).
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Maximum number of bytes to receive in the response.
        /// </summary>
        [Input("receiveMaxBytes")]
        public Input<int>? ReceiveMaxBytes { get; set; }

        /// <summary>
        /// Data to send over the TCP connection.
        /// </summary>
        [Input("send")]
        public Input<string>? Send { get; set; }

        /// <summary>
        /// Timeout for the TCP check (e.g. `5s`, `10s`).
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        public SyntheticTestTcpCheckArgs()
        {
        }
        public static new SyntheticTestTcpCheckArgs Empty => new SyntheticTestTcpCheckArgs();
    }
}
