// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package groundcover

import (
	"context"
	"reflect"

	"errors"
	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Connected App resource for managing integrations with external services.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			groundcoverApiKey := cfg.Require("groundcoverApiKey")
//			groundcoverBackendId := cfg.Require("groundcoverBackendId")
//			slackWebhookUrl := cfg.Require("slackWebhookUrl")
//			pagerdutyRoutingKey := cfg.Require("pagerdutyRoutingKey")
//			slack, err := groundcover.NewConnectedApp(ctx, "slack", &groundcover.ConnectedAppArgs{
//				Type: pulumi.String("slack-webhook"),
//				Data: pulumi.Any(map[string]interface{}{
//					"url": slackWebhookUrl,
//				}),
//			})
//			if err != nil {
//				return err
//			}
//			pagerduty, err := groundcover.NewConnectedApp(ctx, "pagerduty", &groundcover.ConnectedAppArgs{
//				Type: pulumi.String("pagerduty"),
//				Data: pulumi.Any(map[string]interface{}{
//					"routingKey": pagerdutyRoutingKey,
//				}),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = groundcover.NewConnectedApp(ctx, "pagerdutyWithSeverity", &groundcover.ConnectedAppArgs{
//				Type: pulumi.String("pagerduty"),
//				Data: pulumi.Any(map[string]interface{}{
//					"routingKey": pagerdutyRoutingKey,
//					"severityMapping": map[string]interface{}{
//						"critical": "critical",
//						"error":    "error",
//						"warning":  "warning",
//						"info":     "info",
//					},
//				}),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("slackAppId", slack.ID())
//			ctx.Export("pagerdutyAppId", pagerduty.ID())
//			return nil
//		})
//	}
//
// ```
type ConnectedApp struct {
	pulumi.CustomResourceState

	// The date the connected app was created (RFC3339 format).
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The user who created the connected app.
	CreatedBy pulumi.StringOutput `pulumi:"createdBy"`
	// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
	Data pulumi.AnyOutput `pulumi:"data"`
	// Name of the connected app.
	Name pulumi.StringOutput `pulumi:"name"`
	// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
	Type pulumi.StringOutput `pulumi:"type"`
	// The date the connected app was last updated (RFC3339 format).
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The user who last updated the connected app.
	UpdatedBy pulumi.StringOutput `pulumi:"updatedBy"`
}

// NewConnectedApp registers a new resource with the given unique name, arguments, and options.
func NewConnectedApp(ctx *pulumi.Context,
	name string, args *ConnectedAppArgs, opts ...pulumi.ResourceOption) (*ConnectedApp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Data == nil {
		return nil, errors.New("invalid value for required argument 'Data'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Data != nil {
		args.Data = pulumi.ToSecret(args.Data).(pulumi.Input)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"data",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ConnectedApp
	err := ctx.RegisterResource("groundcover:index/connectedApp:ConnectedApp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConnectedApp gets an existing ConnectedApp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConnectedApp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConnectedAppState, opts ...pulumi.ResourceOption) (*ConnectedApp, error) {
	var resource ConnectedApp
	err := ctx.ReadResource("groundcover:index/connectedApp:ConnectedApp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ConnectedApp resources.
type connectedAppState struct {
	// The date the connected app was created (RFC3339 format).
	CreatedAt *string `pulumi:"createdAt"`
	// The user who created the connected app.
	CreatedBy *string `pulumi:"createdBy"`
	// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
	Data interface{} `pulumi:"data"`
	// Name of the connected app.
	Name *string `pulumi:"name"`
	// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
	Type *string `pulumi:"type"`
	// The date the connected app was last updated (RFC3339 format).
	UpdatedAt *string `pulumi:"updatedAt"`
	// The user who last updated the connected app.
	UpdatedBy *string `pulumi:"updatedBy"`
}

type ConnectedAppState struct {
	// The date the connected app was created (RFC3339 format).
	CreatedAt pulumi.StringPtrInput
	// The user who created the connected app.
	CreatedBy pulumi.StringPtrInput
	// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
	Data pulumi.Input
	// Name of the connected app.
	Name pulumi.StringPtrInput
	// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
	Type pulumi.StringPtrInput
	// The date the connected app was last updated (RFC3339 format).
	UpdatedAt pulumi.StringPtrInput
	// The user who last updated the connected app.
	UpdatedBy pulumi.StringPtrInput
}

func (ConnectedAppState) ElementType() reflect.Type {
	return reflect.TypeOf((*connectedAppState)(nil)).Elem()
}

type connectedAppArgs struct {
	// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
	Data interface{} `pulumi:"data"`
	// Name of the connected app.
	Name *string `pulumi:"name"`
	// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a ConnectedApp resource.
type ConnectedAppArgs struct {
	// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
	Data pulumi.Input
	// Name of the connected app.
	Name pulumi.StringPtrInput
	// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
	Type pulumi.StringInput
}

func (ConnectedAppArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*connectedAppArgs)(nil)).Elem()
}

type ConnectedAppInput interface {
	pulumi.Input

	ToConnectedAppOutput() ConnectedAppOutput
	ToConnectedAppOutputWithContext(ctx context.Context) ConnectedAppOutput
}

func (*ConnectedApp) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectedApp)(nil)).Elem()
}

func (i *ConnectedApp) ToConnectedAppOutput() ConnectedAppOutput {
	return i.ToConnectedAppOutputWithContext(context.Background())
}

func (i *ConnectedApp) ToConnectedAppOutputWithContext(ctx context.Context) ConnectedAppOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectedAppOutput)
}

// ConnectedAppArrayInput is an input type that accepts ConnectedAppArray and ConnectedAppArrayOutput values.
// You can construct a concrete instance of `ConnectedAppArrayInput` via:
//
//	ConnectedAppArray{ ConnectedAppArgs{...} }
type ConnectedAppArrayInput interface {
	pulumi.Input

	ToConnectedAppArrayOutput() ConnectedAppArrayOutput
	ToConnectedAppArrayOutputWithContext(context.Context) ConnectedAppArrayOutput
}

type ConnectedAppArray []ConnectedAppInput

func (ConnectedAppArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectedApp)(nil)).Elem()
}

func (i ConnectedAppArray) ToConnectedAppArrayOutput() ConnectedAppArrayOutput {
	return i.ToConnectedAppArrayOutputWithContext(context.Background())
}

func (i ConnectedAppArray) ToConnectedAppArrayOutputWithContext(ctx context.Context) ConnectedAppArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectedAppArrayOutput)
}

// ConnectedAppMapInput is an input type that accepts ConnectedAppMap and ConnectedAppMapOutput values.
// You can construct a concrete instance of `ConnectedAppMapInput` via:
//
//	ConnectedAppMap{ "key": ConnectedAppArgs{...} }
type ConnectedAppMapInput interface {
	pulumi.Input

	ToConnectedAppMapOutput() ConnectedAppMapOutput
	ToConnectedAppMapOutputWithContext(context.Context) ConnectedAppMapOutput
}

type ConnectedAppMap map[string]ConnectedAppInput

func (ConnectedAppMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectedApp)(nil)).Elem()
}

func (i ConnectedAppMap) ToConnectedAppMapOutput() ConnectedAppMapOutput {
	return i.ToConnectedAppMapOutputWithContext(context.Background())
}

func (i ConnectedAppMap) ToConnectedAppMapOutputWithContext(ctx context.Context) ConnectedAppMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConnectedAppMapOutput)
}

type ConnectedAppOutput struct{ *pulumi.OutputState }

func (ConnectedAppOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConnectedApp)(nil)).Elem()
}

func (o ConnectedAppOutput) ToConnectedAppOutput() ConnectedAppOutput {
	return o
}

func (o ConnectedAppOutput) ToConnectedAppOutputWithContext(ctx context.Context) ConnectedAppOutput {
	return o
}

// The date the connected app was created (RFC3339 format).
func (o ConnectedAppOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user who created the connected app.
func (o ConnectedAppOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.CreatedBy }).(pulumi.StringOutput)
}

// Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
func (o ConnectedAppOutput) Data() pulumi.AnyOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.AnyOutput { return v.Data }).(pulumi.AnyOutput)
}

// Name of the connected app.
func (o ConnectedAppOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, or rootly).
func (o ConnectedAppOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The date the connected app was last updated (RFC3339 format).
func (o ConnectedAppOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The user who last updated the connected app.
func (o ConnectedAppOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *ConnectedApp) pulumi.StringOutput { return v.UpdatedBy }).(pulumi.StringOutput)
}

type ConnectedAppArrayOutput struct{ *pulumi.OutputState }

func (ConnectedAppArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ConnectedApp)(nil)).Elem()
}

func (o ConnectedAppArrayOutput) ToConnectedAppArrayOutput() ConnectedAppArrayOutput {
	return o
}

func (o ConnectedAppArrayOutput) ToConnectedAppArrayOutputWithContext(ctx context.Context) ConnectedAppArrayOutput {
	return o
}

func (o ConnectedAppArrayOutput) Index(i pulumi.IntInput) ConnectedAppOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ConnectedApp {
		return vs[0].([]*ConnectedApp)[vs[1].(int)]
	}).(ConnectedAppOutput)
}

type ConnectedAppMapOutput struct{ *pulumi.OutputState }

func (ConnectedAppMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ConnectedApp)(nil)).Elem()
}

func (o ConnectedAppMapOutput) ToConnectedAppMapOutput() ConnectedAppMapOutput {
	return o
}

func (o ConnectedAppMapOutput) ToConnectedAppMapOutputWithContext(ctx context.Context) ConnectedAppMapOutput {
	return o
}

func (o ConnectedAppMapOutput) MapIndex(k pulumi.StringInput) ConnectedAppOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ConnectedApp {
		return vs[0].(map[string]*ConnectedApp)[vs[1].(string)]
	}).(ConnectedAppOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectedAppInput)(nil)).Elem(), &ConnectedApp{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectedAppArrayInput)(nil)).Elem(), ConnectedAppArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ConnectedAppMapInput)(nil)).Elem(), ConnectedAppMap{})
	pulumi.RegisterOutputType(ConnectedAppOutput{})
	pulumi.RegisterOutputType(ConnectedAppArrayOutput{})
	pulumi.RegisterOutputType(ConnectedAppMapOutput{})
}
