// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package groundcover

import (
	"context"
	"reflect"

	"errors"
	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a groundcover Recurring Silence.
//
// Recurring silences allow you to automatically suppress alerts on a repeating schedule based on matching criteria. This is useful for planned maintenance windows, recurring deployments, or other predictable situations where you want to regularly mute alerts.
//
// A recurring silence is defined by: a recurrence schedule (daily, weekly, or monthly), a time window (start_time, end_time) in a specific timezone, an optional comment, and one or more matchers that define which alerts to silence.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			groundcoverApiKey := cfg.Require("groundcoverApiKey")
//			groundcoverBackendId := cfg.Require("groundcoverBackendId")
//			// Example 1: Daily recurring silence for nightly maintenance
//			// Silences alerts every day from 2 AM to 4 AM UTC
//			nightlyMaintenance, err := groundcover.NewRecurringSilence(ctx, "nightlyMaintenance", &groundcover.RecurringSilenceArgs{
//				Comment:        pulumi.String("Nightly maintenance window for payment-service"),
//				RecurrenceType: pulumi.String("daily"),
//				StartTime:      pulumi.String("02:00"),
//				EndTime:        pulumi.String("04:00"),
//				Timezone:       pulumi.String("UTC"),
//				Matchers: groundcover.RecurringSilenceMatcherArray{
//					&groundcover.RecurringSilenceMatcherArgs{
//						Name:        pulumi.String("service"),
//						Value:       pulumi.String("payment-service"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 2: Weekly recurring silence for deployment windows
//			// Silences alerts every Monday and Wednesday from 9 AM to 11 AM Eastern
//			deploymentWindow, err := groundcover.NewRecurringSilence(ctx, "deploymentWindow", &groundcover.RecurringSilenceArgs{
//				Comment:        pulumi.String("Scheduled deployment window"),
//				RecurrenceType: pulumi.String("weekly"),
//				StartTime:      pulumi.String("09:00"),
//				EndTime:        pulumi.String("11:00"),
//				Timezone:       pulumi.String("America/New_York"),
//				DaysOfWeeks: pulumi.IntArray{
//					pulumi.Int(1),
//					pulumi.Int(3),
//				},
//				Matchers: groundcover.RecurringSilenceMatcherArray{
//					&groundcover.RecurringSilenceMatcherArgs{
//						Name:        pulumi.String("workload"),
//						Value:       pulumi.String("api-gateway"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//					&groundcover.RecurringSilenceMatcherArgs{
//						Name:        pulumi.String("environment"),
//						Value:       pulumi.String("staging"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 3: Monthly recurring silence with contains pattern
//			// Silences alerts on the 1st and 15th of each month from 10 PM to 6 AM (overnight)
//			_, err = groundcover.NewRecurringSilence(ctx, "patchDay", &groundcover.RecurringSilenceArgs{
//				Comment:        pulumi.String("Monthly patch day - overnight maintenance"),
//				RecurrenceType: pulumi.String("monthly"),
//				StartTime:      pulumi.String("22:00"),
//				EndTime:        pulumi.String("06:00"),
//				Timezone:       pulumi.String("Europe/London"),
//				DaysOfMonths: pulumi.IntArray{
//					pulumi.Int(1),
//					pulumi.Int(15),
//				},
//				Matchers: groundcover.RecurringSilenceMatcherArray{
//					&groundcover.RecurringSilenceMatcherArgs{
//						Name:        pulumi.String("service"),
//						Value:       pulumi.String("app-dev"),
//						Is_equal:    true,
//						Is_contains: true,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 4: Disabled recurring silence with negation (is_equal = false)
//			// Silences all alerts EXCEPT for production environment
//			_, err = groundcover.NewRecurringSilence(ctx, "weekendSilence", &groundcover.RecurringSilenceArgs{
//				Comment:        pulumi.String("Weekend silence - currently disabled"),
//				RecurrenceType: pulumi.String("weekly"),
//				StartTime:      pulumi.String("00:00"),
//				EndTime:        pulumi.String("23:59"),
//				Timezone:       pulumi.String("UTC"),
//				DaysOfWeeks: pulumi.IntArray{
//					pulumi.Int(0),
//					pulumi.Int(6),
//				},
//				Enabled: pulumi.Bool(false),
//				Matchers: groundcover.RecurringSilenceMatcherArray{
//					&groundcover.RecurringSilenceMatcherArgs{
//						Name:        pulumi.String("environment"),
//						Value:       pulumi.String("production"),
//						Is_equal:    false,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("nightlyMaintenanceId", nightlyMaintenance.ID())
//			ctx.Export("deploymentWindowId", deploymentWindow.ID())
//			return nil
//		})
//	}
//
// ```
type RecurringSilence struct {
	pulumi.CustomResourceState

	// A comment describing the reason for the recurring silence.
	Comment pulumi.StringOutput `pulumi:"comment"`
	// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
	DaysOfMonths pulumi.IntArrayOutput `pulumi:"daysOfMonths"`
	// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
	DaysOfWeeks pulumi.IntArrayOutput `pulumi:"daysOfWeeks"`
	// Whether the recurring silence is enabled. Defaults to `true`.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
	EndTime pulumi.StringOutput `pulumi:"endTime"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers RecurringSilenceMatcherArrayOutput `pulumi:"matchers"`
	// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
	RecurrenceType pulumi.StringOutput `pulumi:"recurrenceType"`
	// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
	StartTime pulumi.StringOutput `pulumi:"startTime"`
	// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
	Timezone pulumi.StringOutput `pulumi:"timezone"`
}

// NewRecurringSilence registers a new resource with the given unique name, arguments, and options.
func NewRecurringSilence(ctx *pulumi.Context,
	name string, args *RecurringSilenceArgs, opts ...pulumi.ResourceOption) (*RecurringSilence, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EndTime == nil {
		return nil, errors.New("invalid value for required argument 'EndTime'")
	}
	if args.Matchers == nil {
		return nil, errors.New("invalid value for required argument 'Matchers'")
	}
	if args.RecurrenceType == nil {
		return nil, errors.New("invalid value for required argument 'RecurrenceType'")
	}
	if args.StartTime == nil {
		return nil, errors.New("invalid value for required argument 'StartTime'")
	}
	if args.Timezone == nil {
		return nil, errors.New("invalid value for required argument 'Timezone'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RecurringSilence
	err := ctx.RegisterResource("groundcover:index/recurringSilence:RecurringSilence", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecurringSilence gets an existing RecurringSilence resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecurringSilence(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecurringSilenceState, opts ...pulumi.ResourceOption) (*RecurringSilence, error) {
	var resource RecurringSilence
	err := ctx.ReadResource("groundcover:index/recurringSilence:RecurringSilence", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RecurringSilence resources.
type recurringSilenceState struct {
	// A comment describing the reason for the recurring silence.
	Comment *string `pulumi:"comment"`
	// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
	DaysOfMonths []int `pulumi:"daysOfMonths"`
	// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
	DaysOfWeeks []int `pulumi:"daysOfWeeks"`
	// Whether the recurring silence is enabled. Defaults to `true`.
	Enabled *bool `pulumi:"enabled"`
	// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
	EndTime *string `pulumi:"endTime"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers []RecurringSilenceMatcher `pulumi:"matchers"`
	// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
	RecurrenceType *string `pulumi:"recurrenceType"`
	// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
	StartTime *string `pulumi:"startTime"`
	// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
	Timezone *string `pulumi:"timezone"`
}

type RecurringSilenceState struct {
	// A comment describing the reason for the recurring silence.
	Comment pulumi.StringPtrInput
	// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
	DaysOfMonths pulumi.IntArrayInput
	// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
	DaysOfWeeks pulumi.IntArrayInput
	// Whether the recurring silence is enabled. Defaults to `true`.
	Enabled pulumi.BoolPtrInput
	// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
	EndTime pulumi.StringPtrInput
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers RecurringSilenceMatcherArrayInput
	// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
	RecurrenceType pulumi.StringPtrInput
	// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
	StartTime pulumi.StringPtrInput
	// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
	Timezone pulumi.StringPtrInput
}

func (RecurringSilenceState) ElementType() reflect.Type {
	return reflect.TypeOf((*recurringSilenceState)(nil)).Elem()
}

type recurringSilenceArgs struct {
	// A comment describing the reason for the recurring silence.
	Comment *string `pulumi:"comment"`
	// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
	DaysOfMonths []int `pulumi:"daysOfMonths"`
	// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
	DaysOfWeeks []int `pulumi:"daysOfWeeks"`
	// Whether the recurring silence is enabled. Defaults to `true`.
	Enabled *bool `pulumi:"enabled"`
	// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
	EndTime string `pulumi:"endTime"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers []RecurringSilenceMatcher `pulumi:"matchers"`
	// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
	RecurrenceType string `pulumi:"recurrenceType"`
	// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
	StartTime string `pulumi:"startTime"`
	// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
	Timezone string `pulumi:"timezone"`
}

// The set of arguments for constructing a RecurringSilence resource.
type RecurringSilenceArgs struct {
	// A comment describing the reason for the recurring silence.
	Comment pulumi.StringPtrInput
	// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
	DaysOfMonths pulumi.IntArrayInput
	// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
	DaysOfWeeks pulumi.IntArrayInput
	// Whether the recurring silence is enabled. Defaults to `true`.
	Enabled pulumi.BoolPtrInput
	// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
	EndTime pulumi.StringInput
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers RecurringSilenceMatcherArrayInput
	// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
	RecurrenceType pulumi.StringInput
	// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
	StartTime pulumi.StringInput
	// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
	Timezone pulumi.StringInput
}

func (RecurringSilenceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recurringSilenceArgs)(nil)).Elem()
}

type RecurringSilenceInput interface {
	pulumi.Input

	ToRecurringSilenceOutput() RecurringSilenceOutput
	ToRecurringSilenceOutputWithContext(ctx context.Context) RecurringSilenceOutput
}

func (*RecurringSilence) ElementType() reflect.Type {
	return reflect.TypeOf((**RecurringSilence)(nil)).Elem()
}

func (i *RecurringSilence) ToRecurringSilenceOutput() RecurringSilenceOutput {
	return i.ToRecurringSilenceOutputWithContext(context.Background())
}

func (i *RecurringSilence) ToRecurringSilenceOutputWithContext(ctx context.Context) RecurringSilenceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecurringSilenceOutput)
}

// RecurringSilenceArrayInput is an input type that accepts RecurringSilenceArray and RecurringSilenceArrayOutput values.
// You can construct a concrete instance of `RecurringSilenceArrayInput` via:
//
//	RecurringSilenceArray{ RecurringSilenceArgs{...} }
type RecurringSilenceArrayInput interface {
	pulumi.Input

	ToRecurringSilenceArrayOutput() RecurringSilenceArrayOutput
	ToRecurringSilenceArrayOutputWithContext(context.Context) RecurringSilenceArrayOutput
}

type RecurringSilenceArray []RecurringSilenceInput

func (RecurringSilenceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecurringSilence)(nil)).Elem()
}

func (i RecurringSilenceArray) ToRecurringSilenceArrayOutput() RecurringSilenceArrayOutput {
	return i.ToRecurringSilenceArrayOutputWithContext(context.Background())
}

func (i RecurringSilenceArray) ToRecurringSilenceArrayOutputWithContext(ctx context.Context) RecurringSilenceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecurringSilenceArrayOutput)
}

// RecurringSilenceMapInput is an input type that accepts RecurringSilenceMap and RecurringSilenceMapOutput values.
// You can construct a concrete instance of `RecurringSilenceMapInput` via:
//
//	RecurringSilenceMap{ "key": RecurringSilenceArgs{...} }
type RecurringSilenceMapInput interface {
	pulumi.Input

	ToRecurringSilenceMapOutput() RecurringSilenceMapOutput
	ToRecurringSilenceMapOutputWithContext(context.Context) RecurringSilenceMapOutput
}

type RecurringSilenceMap map[string]RecurringSilenceInput

func (RecurringSilenceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecurringSilence)(nil)).Elem()
}

func (i RecurringSilenceMap) ToRecurringSilenceMapOutput() RecurringSilenceMapOutput {
	return i.ToRecurringSilenceMapOutputWithContext(context.Background())
}

func (i RecurringSilenceMap) ToRecurringSilenceMapOutputWithContext(ctx context.Context) RecurringSilenceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecurringSilenceMapOutput)
}

type RecurringSilenceOutput struct{ *pulumi.OutputState }

func (RecurringSilenceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RecurringSilence)(nil)).Elem()
}

func (o RecurringSilenceOutput) ToRecurringSilenceOutput() RecurringSilenceOutput {
	return o
}

func (o RecurringSilenceOutput) ToRecurringSilenceOutputWithContext(ctx context.Context) RecurringSilenceOutput {
	return o
}

// A comment describing the reason for the recurring silence.
func (o RecurringSilenceOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.StringOutput { return v.Comment }).(pulumi.StringOutput)
}

// Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
func (o RecurringSilenceOutput) DaysOfMonths() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.IntArrayOutput { return v.DaysOfMonths }).(pulumi.IntArrayOutput)
}

// Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
func (o RecurringSilenceOutput) DaysOfWeeks() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.IntArrayOutput { return v.DaysOfWeeks }).(pulumi.IntArrayOutput)
}

// Whether the recurring silence is enabled. Defaults to `true`.
func (o RecurringSilenceOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
func (o RecurringSilenceOutput) EndTime() pulumi.StringOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.StringOutput { return v.EndTime }).(pulumi.StringOutput)
}

// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
func (o RecurringSilenceOutput) Matchers() RecurringSilenceMatcherArrayOutput {
	return o.ApplyT(func(v *RecurringSilence) RecurringSilenceMatcherArrayOutput { return v.Matchers }).(RecurringSilenceMatcherArrayOutput)
}

// The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
func (o RecurringSilenceOutput) RecurrenceType() pulumi.StringOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.StringOutput { return v.RecurrenceType }).(pulumi.StringOutput)
}

// The start time of the silence window in `HH:MM` format (e.g., `09:00`).
func (o RecurringSilenceOutput) StartTime() pulumi.StringOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.StringOutput { return v.StartTime }).(pulumi.StringOutput)
}

// The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
func (o RecurringSilenceOutput) Timezone() pulumi.StringOutput {
	return o.ApplyT(func(v *RecurringSilence) pulumi.StringOutput { return v.Timezone }).(pulumi.StringOutput)
}

type RecurringSilenceArrayOutput struct{ *pulumi.OutputState }

func (RecurringSilenceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecurringSilence)(nil)).Elem()
}

func (o RecurringSilenceArrayOutput) ToRecurringSilenceArrayOutput() RecurringSilenceArrayOutput {
	return o
}

func (o RecurringSilenceArrayOutput) ToRecurringSilenceArrayOutputWithContext(ctx context.Context) RecurringSilenceArrayOutput {
	return o
}

func (o RecurringSilenceArrayOutput) Index(i pulumi.IntInput) RecurringSilenceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RecurringSilence {
		return vs[0].([]*RecurringSilence)[vs[1].(int)]
	}).(RecurringSilenceOutput)
}

type RecurringSilenceMapOutput struct{ *pulumi.OutputState }

func (RecurringSilenceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecurringSilence)(nil)).Elem()
}

func (o RecurringSilenceMapOutput) ToRecurringSilenceMapOutput() RecurringSilenceMapOutput {
	return o
}

func (o RecurringSilenceMapOutput) ToRecurringSilenceMapOutputWithContext(ctx context.Context) RecurringSilenceMapOutput {
	return o
}

func (o RecurringSilenceMapOutput) MapIndex(k pulumi.StringInput) RecurringSilenceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RecurringSilence {
		return vs[0].(map[string]*RecurringSilence)[vs[1].(string)]
	}).(RecurringSilenceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecurringSilenceInput)(nil)).Elem(), &RecurringSilence{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecurringSilenceArrayInput)(nil)).Elem(), RecurringSilenceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecurringSilenceMapInput)(nil)).Elem(), RecurringSilenceMap{})
	pulumi.RegisterOutputType(RecurringSilenceOutput{})
	pulumi.RegisterOutputType(RecurringSilenceArrayOutput{})
	pulumi.RegisterOutputType(RecurringSilenceMapOutput{})
}
