// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package groundcover

import (
	"context"
	"reflect"

	"errors"
	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a groundcover Silence.
//
// Silences allow you to suppress alerts for a specific time window based on matching criteria. This is useful for planned maintenance, deployments, or other situations where you want to temporarily mute alerts.
//
// A silence is defined by: a time window (starts_at, ends_at), a comment describing the reason for the silence, and one or more matchers that define which alerts to silence.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/groundcover-com/pulumi-groundcover/sdk/go/groundcover"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			groundcoverApiKey := cfg.Require("groundcoverApiKey")
//			groundcoverBackendId := cfg.Require("groundcoverBackendId")
//			// Example 1: Simple silence for planned maintenance
//			// Silences all alerts for a specific service during a maintenance window
//			maintenanceWindow, err := groundcover.NewSilence(ctx, "maintenanceWindow", &groundcover.SilenceArgs{
//				StartsAt: pulumi.String("2030-01-15T10:00:00Z"),
//				EndsAt:   pulumi.String("2030-01-15T14:00:00Z"),
//				Comment:  pulumi.String("Planned maintenance window for payment-service"),
//				Matchers: groundcover.SilenceMatcherArray{
//					&groundcover.SilenceMatcherArgs{
//						Name:        pulumi.String("service"),
//						Value:       pulumi.String("payment-service"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 2: Silence with multiple matchers
//			// Silences alerts for a specific workload in a specific environment
//			deploymentSilence, err := groundcover.NewSilence(ctx, "deploymentSilence", &groundcover.SilenceArgs{
//				StartsAt: pulumi.String("2030-01-20T08:00:00Z"),
//				EndsAt:   pulumi.String("2030-01-20T10:00:00Z"),
//				Comment:  pulumi.String("Deploying new version of api-gateway in staging"),
//				Matchers: groundcover.SilenceMatcherArray{
//					&groundcover.SilenceMatcherArgs{
//						Name:        pulumi.String("workload"),
//						Value:       pulumi.String("api-gateway"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//					&groundcover.SilenceMatcherArgs{
//						Name:        pulumi.String("environment"),
//						Value:       pulumi.String("staging"),
//						Is_equal:    true,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 3: Silence with contains pattern (starts_at and ends_at are UTC 0)
//			// Silences alerts for any service containing the specified value
//			_, err = groundcover.NewSilence(ctx, "testServicesSilence", &groundcover.SilenceArgs{
//				StartsAt: pulumi.String("2030-02-01T00:00:00Z"),
//				EndsAt:   pulumi.String("2030-02-01T06:00:00Z"),
//				Comment:  pulumi.String("Overnight testing - silence all test services"),
//				Matchers: groundcover.SilenceMatcherArray{
//					&groundcover.SilenceMatcherArgs{
//						Name:        pulumi.String("service"),
//						Value:       pulumi.String("app-dev"),
//						Is_equal:    true,
//						Is_contains: true,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Example 4: Silence with negation (is_equal = false)
//			// Silences all alerts EXCEPT for production environment
//			_, err = groundcover.NewSilence(ctx, "nonProductionSilence", &groundcover.SilenceArgs{
//				StartsAt: pulumi.String("2030-03-01T12:00:00Z"),
//				EndsAt:   pulumi.String("2030-03-01T18:00:00Z"),
//				Comment:  pulumi.String("Silence non-production alerts during load testing"),
//				Matchers: groundcover.SilenceMatcherArray{
//					&groundcover.SilenceMatcherArgs{
//						Name:        pulumi.String("environment"),
//						Value:       pulumi.String("production"),
//						Is_equal:    false,
//						Is_contains: false,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("maintenanceSilenceId", maintenanceWindow.ID())
//			ctx.Export("deploymentSilenceId", deploymentSilence.ID())
//			return nil
//		})
//	}
//
// ```
type Silence struct {
	pulumi.CustomResourceState

	// A comment describing the reason for the silence.
	Comment pulumi.StringOutput `pulumi:"comment"`
	// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
	EndsAt pulumi.StringOutput `pulumi:"endsAt"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers SilenceMatcherArrayOutput `pulumi:"matchers"`
	// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
	StartsAt pulumi.StringOutput `pulumi:"startsAt"`
}

// NewSilence registers a new resource with the given unique name, arguments, and options.
func NewSilence(ctx *pulumi.Context,
	name string, args *SilenceArgs, opts ...pulumi.ResourceOption) (*Silence, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EndsAt == nil {
		return nil, errors.New("invalid value for required argument 'EndsAt'")
	}
	if args.Matchers == nil {
		return nil, errors.New("invalid value for required argument 'Matchers'")
	}
	if args.StartsAt == nil {
		return nil, errors.New("invalid value for required argument 'StartsAt'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Silence
	err := ctx.RegisterResource("groundcover:index/silence:Silence", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSilence gets an existing Silence resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSilence(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SilenceState, opts ...pulumi.ResourceOption) (*Silence, error) {
	var resource Silence
	err := ctx.ReadResource("groundcover:index/silence:Silence", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Silence resources.
type silenceState struct {
	// A comment describing the reason for the silence.
	Comment *string `pulumi:"comment"`
	// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
	EndsAt *string `pulumi:"endsAt"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers []SilenceMatcher `pulumi:"matchers"`
	// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
	StartsAt *string `pulumi:"startsAt"`
}

type SilenceState struct {
	// A comment describing the reason for the silence.
	Comment pulumi.StringPtrInput
	// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
	EndsAt pulumi.StringPtrInput
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers SilenceMatcherArrayInput
	// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
	StartsAt pulumi.StringPtrInput
}

func (SilenceState) ElementType() reflect.Type {
	return reflect.TypeOf((*silenceState)(nil)).Elem()
}

type silenceArgs struct {
	// A comment describing the reason for the silence.
	Comment *string `pulumi:"comment"`
	// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
	EndsAt string `pulumi:"endsAt"`
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers []SilenceMatcher `pulumi:"matchers"`
	// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
	StartsAt string `pulumi:"startsAt"`
}

// The set of arguments for constructing a Silence resource.
type SilenceArgs struct {
	// A comment describing the reason for the silence.
	Comment pulumi.StringPtrInput
	// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
	EndsAt pulumi.StringInput
	// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
	Matchers SilenceMatcherArrayInput
	// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
	StartsAt pulumi.StringInput
}

func (SilenceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*silenceArgs)(nil)).Elem()
}

type SilenceInput interface {
	pulumi.Input

	ToSilenceOutput() SilenceOutput
	ToSilenceOutputWithContext(ctx context.Context) SilenceOutput
}

func (*Silence) ElementType() reflect.Type {
	return reflect.TypeOf((**Silence)(nil)).Elem()
}

func (i *Silence) ToSilenceOutput() SilenceOutput {
	return i.ToSilenceOutputWithContext(context.Background())
}

func (i *Silence) ToSilenceOutputWithContext(ctx context.Context) SilenceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SilenceOutput)
}

// SilenceArrayInput is an input type that accepts SilenceArray and SilenceArrayOutput values.
// You can construct a concrete instance of `SilenceArrayInput` via:
//
//	SilenceArray{ SilenceArgs{...} }
type SilenceArrayInput interface {
	pulumi.Input

	ToSilenceArrayOutput() SilenceArrayOutput
	ToSilenceArrayOutputWithContext(context.Context) SilenceArrayOutput
}

type SilenceArray []SilenceInput

func (SilenceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Silence)(nil)).Elem()
}

func (i SilenceArray) ToSilenceArrayOutput() SilenceArrayOutput {
	return i.ToSilenceArrayOutputWithContext(context.Background())
}

func (i SilenceArray) ToSilenceArrayOutputWithContext(ctx context.Context) SilenceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SilenceArrayOutput)
}

// SilenceMapInput is an input type that accepts SilenceMap and SilenceMapOutput values.
// You can construct a concrete instance of `SilenceMapInput` via:
//
//	SilenceMap{ "key": SilenceArgs{...} }
type SilenceMapInput interface {
	pulumi.Input

	ToSilenceMapOutput() SilenceMapOutput
	ToSilenceMapOutputWithContext(context.Context) SilenceMapOutput
}

type SilenceMap map[string]SilenceInput

func (SilenceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Silence)(nil)).Elem()
}

func (i SilenceMap) ToSilenceMapOutput() SilenceMapOutput {
	return i.ToSilenceMapOutputWithContext(context.Background())
}

func (i SilenceMap) ToSilenceMapOutputWithContext(ctx context.Context) SilenceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SilenceMapOutput)
}

type SilenceOutput struct{ *pulumi.OutputState }

func (SilenceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Silence)(nil)).Elem()
}

func (o SilenceOutput) ToSilenceOutput() SilenceOutput {
	return o
}

func (o SilenceOutput) ToSilenceOutputWithContext(ctx context.Context) SilenceOutput {
	return o
}

// A comment describing the reason for the silence.
func (o SilenceOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v *Silence) pulumi.StringOutput { return v.Comment }).(pulumi.StringOutput)
}

// The end time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T12:00:00Z`).
func (o SilenceOutput) EndsAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Silence) pulumi.StringOutput { return v.EndsAt }).(pulumi.StringOutput)
}

// A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
func (o SilenceOutput) Matchers() SilenceMatcherArrayOutput {
	return o.ApplyT(func(v *Silence) SilenceMatcherArrayOutput { return v.Matchers }).(SilenceMatcherArrayOutput)
}

// The start time of the silence in RFC3339 format UTC 0 (e.g., `2024-01-15T10:00:00Z`).
func (o SilenceOutput) StartsAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Silence) pulumi.StringOutput { return v.StartsAt }).(pulumi.StringOutput)
}

type SilenceArrayOutput struct{ *pulumi.OutputState }

func (SilenceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Silence)(nil)).Elem()
}

func (o SilenceArrayOutput) ToSilenceArrayOutput() SilenceArrayOutput {
	return o
}

func (o SilenceArrayOutput) ToSilenceArrayOutputWithContext(ctx context.Context) SilenceArrayOutput {
	return o
}

func (o SilenceArrayOutput) Index(i pulumi.IntInput) SilenceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Silence {
		return vs[0].([]*Silence)[vs[1].(int)]
	}).(SilenceOutput)
}

type SilenceMapOutput struct{ *pulumi.OutputState }

func (SilenceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Silence)(nil)).Elem()
}

func (o SilenceMapOutput) ToSilenceMapOutput() SilenceMapOutput {
	return o
}

func (o SilenceMapOutput) ToSilenceMapOutputWithContext(ctx context.Context) SilenceMapOutput {
	return o
}

func (o SilenceMapOutput) MapIndex(k pulumi.StringInput) SilenceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Silence {
		return vs[0].(map[string]*Silence)[vs[1].(string)]
	}).(SilenceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SilenceInput)(nil)).Elem(), &Silence{})
	pulumi.RegisterInputType(reflect.TypeOf((*SilenceArrayInput)(nil)).Elem(), SilenceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SilenceMapInput)(nil)).Elem(), SilenceMap{})
	pulumi.RegisterOutputType(SilenceOutput{})
	pulumi.RegisterOutputType(SilenceArrayOutput{})
	pulumi.RegisterOutputType(SilenceMapOutput{})
}
