// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * API Key resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * // Example Policy (required for Service Account)
 * const examplePolicy = new groundcover.Policy("examplePolicy", {
 *     role: {
 *         read: "read",
 *     },
 *     description: "Example policy for api key resource example.",
 * });
 * // Example Service Account (required for API Key)
 * const exampleServiceaccount = new groundcover.Serviceaccount("exampleServiceaccount", {policyUuids: [examplePolicy.uuid]});
 * // Example API Key
 * const exampleApikey = new groundcover.Apikey("exampleApikey", {
 *     description: "API Key generated via Terraform example.",
 *     serviceAccountId: exampleServiceaccount.id,
 * });
 * // Optional: Set an expiration date (RFC3339 format)
 * // expiration_date  = "2025-01-01T00:00:00Z"
 * export const apikeyExampleId = exampleApikey.id;
 * export const apikeyExampleValue = exampleApikey.apiKey;
 * export const apikeyExampleCreationDate = exampleApikey.creationDate;
 * ```
 */
export class Apikey extends pulumi.CustomResource {
    /**
     * Get an existing Apikey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApikeyState, opts?: pulumi.CustomResourceOptions): Apikey {
        return new Apikey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/apikey:Apikey';

    /**
     * Returns true if the given object is an instance of Apikey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Apikey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Apikey.__pulumiType;
    }

    /**
     * The generated API key. This value is only available upon creation.
     */
    declare public /*out*/ readonly apiKey: pulumi.Output<string>;
    /**
     * The user who created the API key.
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<string>;
    /**
     * The date the API key was created (RFC3339 format).
     */
    declare public /*out*/ readonly creationDate: pulumi.Output<string>;
    /**
     * A description for the API key.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The expiration date for the API key (RFC3339 format). If not set, the key never expires.
     */
    declare public readonly expirationDate: pulumi.Output<string | undefined>;
    /**
     * The date the API key expired (RFC3339 format), based on the 'expiration_date' set.
     */
    declare public /*out*/ readonly expiredAt: pulumi.Output<string>;
    /**
     * The last time the API key was active (RFC3339 format).
     */
    declare public /*out*/ readonly lastActive: pulumi.Output<string>;
    /**
     * The name of the API key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Policies associated with the service account linked to this API key.
     */
    declare public /*out*/ readonly policies: pulumi.Output<outputs.ApikeyPolicy[]>;
    /**
     * The date the API key was revoked (RFC3339 format), if applicable.
     */
    declare public /*out*/ readonly revokedAt: pulumi.Output<string>;
    /**
     * The ID of the service account associated with the API key.
     */
    declare public readonly serviceAccountId: pulumi.Output<string>;

    /**
     * Create a Apikey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApikeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApikeyArgs | ApikeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApikeyState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["creationDate"] = state?.creationDate;
            resourceInputs["description"] = state?.description;
            resourceInputs["expirationDate"] = state?.expirationDate;
            resourceInputs["expiredAt"] = state?.expiredAt;
            resourceInputs["lastActive"] = state?.lastActive;
            resourceInputs["name"] = state?.name;
            resourceInputs["policies"] = state?.policies;
            resourceInputs["revokedAt"] = state?.revokedAt;
            resourceInputs["serviceAccountId"] = state?.serviceAccountId;
        } else {
            const args = argsOrState as ApikeyArgs | undefined;
            if (args?.serviceAccountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceAccountId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["expirationDate"] = args?.expirationDate;
            resourceInputs["name"] = args?.name;
            resourceInputs["serviceAccountId"] = args?.serviceAccountId;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["expiredAt"] = undefined /*out*/;
            resourceInputs["lastActive"] = undefined /*out*/;
            resourceInputs["policies"] = undefined /*out*/;
            resourceInputs["revokedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Apikey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Apikey resources.
 */
export interface ApikeyState {
    /**
     * The generated API key. This value is only available upon creation.
     */
    apiKey?: pulumi.Input<string>;
    /**
     * The user who created the API key.
     */
    createdBy?: pulumi.Input<string>;
    /**
     * The date the API key was created (RFC3339 format).
     */
    creationDate?: pulumi.Input<string>;
    /**
     * A description for the API key.
     */
    description?: pulumi.Input<string>;
    /**
     * The expiration date for the API key (RFC3339 format). If not set, the key never expires.
     */
    expirationDate?: pulumi.Input<string>;
    /**
     * The date the API key expired (RFC3339 format), based on the 'expiration_date' set.
     */
    expiredAt?: pulumi.Input<string>;
    /**
     * The last time the API key was active (RFC3339 format).
     */
    lastActive?: pulumi.Input<string>;
    /**
     * The name of the API key.
     */
    name?: pulumi.Input<string>;
    /**
     * Policies associated with the service account linked to this API key.
     */
    policies?: pulumi.Input<pulumi.Input<inputs.ApikeyPolicy>[]>;
    /**
     * The date the API key was revoked (RFC3339 format), if applicable.
     */
    revokedAt?: pulumi.Input<string>;
    /**
     * The ID of the service account associated with the API key.
     */
    serviceAccountId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Apikey resource.
 */
export interface ApikeyArgs {
    /**
     * A description for the API key.
     */
    description?: pulumi.Input<string>;
    /**
     * The expiration date for the API key (RFC3339 format). If not set, the key never expires.
     */
    expirationDate?: pulumi.Input<string>;
    /**
     * The name of the API key.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the service account associated with the API key.
     */
    serviceAccountId: pulumi.Input<string>;
}
