// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Connected App resource for managing integrations with external services.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * const slackWebhookUrl = config.require("slackWebhookUrl");
 * const pagerdutyRoutingKey = config.require("pagerdutyRoutingKey");
 * const msTeamsWebhookUrl = config.require("msTeamsWebhookUrl");
 * const slack = new groundcover.ConnectedApp("slack", {
 *     type: "slack-webhook",
 *     data: {
 *         url: slackWebhookUrl,
 *     },
 * });
 * const msTeams = new groundcover.ConnectedApp("msTeams", {
 *     type: "ms-teams",
 *     data: {
 *         url: msTeamsWebhookUrl,
 *     },
 * });
 * const pagerduty = new groundcover.ConnectedApp("pagerduty", {
 *     type: "pagerduty",
 *     data: {
 *         routingKey: pagerdutyRoutingKey,
 *     },
 * });
 * const pagerdutyWithSeverity = new groundcover.ConnectedApp("pagerdutyWithSeverity", {
 *     type: "pagerduty",
 *     data: {
 *         routingKey: pagerdutyRoutingKey,
 *         severityMapping: {
 *             critical: "critical",
 *             error: "error",
 *             warning: "warning",
 *             info: "info",
 *         },
 *     },
 * });
 * export const slackAppId = slack.id;
 * export const pagerdutyAppId = pagerduty.id;
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import groundcover:index/connectedApp:ConnectedApp example "<id>"
 * ```
 */
export class ConnectedApp extends pulumi.CustomResource {
    /**
     * Get an existing ConnectedApp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectedAppState, opts?: pulumi.CustomResourceOptions): ConnectedApp {
        return new ConnectedApp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/connectedApp:ConnectedApp';

    /**
     * Returns true if the given object is an instance of ConnectedApp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectedApp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectedApp.__pulumiType;
    }

    /**
     * The date the connected app was created (RFC3339 format).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The user who created the connected app.
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<string>;
    /**
     * Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For ms-teams: {url = "https://..."}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
     */
    declare public readonly data: pulumi.Output<any>;
    /**
     * Name of the connected app.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, rootly, or ms-teams).
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * The date the connected app was last updated (RFC3339 format).
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The user who last updated the connected app.
     */
    declare public /*out*/ readonly updatedBy: pulumi.Output<string>;

    /**
     * Create a ConnectedApp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectedAppArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectedAppArgs | ConnectedAppState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectedAppState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["data"] = state?.data;
            resourceInputs["name"] = state?.name;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["updatedBy"] = state?.updatedBy;
        } else {
            const args = argsOrState as ConnectedAppArgs | undefined;
            if (args?.data === undefined && !opts.urn) {
                throw new Error("Missing required property 'data'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["data"] = args?.data ? pulumi.secret(args.data) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["updatedBy"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["data"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ConnectedApp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConnectedApp resources.
 */
export interface ConnectedAppState {
    /**
     * The date the connected app was created (RFC3339 format).
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The user who created the connected app.
     */
    createdBy?: pulumi.Input<string>;
    /**
     * Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For ms-teams: {url = "https://..."}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
     */
    data?: any;
    /**
     * Name of the connected app.
     */
    name?: pulumi.Input<string>;
    /**
     * Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, rootly, or ms-teams).
     */
    type?: pulumi.Input<string>;
    /**
     * The date the connected app was last updated (RFC3339 format).
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * The user who last updated the connected app.
     */
    updatedBy?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ConnectedApp resource.
 */
export interface ConnectedAppArgs {
    /**
     * Type-specific configuration. Supports nested structures. For slack-webhook: {url = "https://..."}. For pagerduty: {routing*key = "...", severity*mapping = {critical = "P1", ...}}. For rootly: {api*key = "...", webhook*url = "https://..."}. For opsgenie: {api*key = "...", region = "us", priority*mapping = {critical = "P1", ...}}. For incidentio: {url = "https://...", severity*mapping = {critical = "SEV0", ...}}. For ms-teams: {url = "https://..."}. For webhook: {url = "https://...", method = "POST" (GET/POST/PUT/DELETE), headers = {key = "value"}, auth*type = "bearer"|"basic", api*key = "..." (for bearer), username = "...", password = "..." (for basic), custom*payload = "JSON Jinja2 template string (max 64KB)"}.
     */
    data: any;
    /**
     * Name of the connected app.
     */
    name?: pulumi.Input<string>;
    /**
     * Type of connected app (slack-webhook, pagerduty, opsgenie, incidentio, webhook, rootly, or ms-teams).
     */
    type: pulumi.Input<string>;
}
