// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * DataIntegration resource for managing groundcover's integrations with external services such as cloud providers, databases and more. This resource is composed of general metadata on the integration and a specific configuration per data source. Navigate to the relevant nested schema according to your specific needs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@pulumiverse/groundcover";
 *
 * // Example: CloudWatch DataIntegration
 * // For a full list of supported AWS metrics and statistics, visit the official CloudWatch documentation:
 * // https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html
 * const cloudwatchExample = new groundcover.Dataintegration("cloudwatchExample", {
 *     type: "cloudwatch",
 *     config: JSON.stringify({
 *         name: "test-cloudwatch",
 *         version: 1,
 *         stsRegion: "us-east-1",
 *         regions: [
 *             "us-east-1",
 *             "us-east-2",
 *         ],
 *         roleArn: "arn:aws:iam::123456789012:role/test-role",
 *         awsMetrics: [{
 *             namespace: "AWS/EC2",
 *             metrics: [{
 *                 name: "CPUUtilization",
 *                 statistics: ["Average"],
 *             }],
 *         }],
 *         labelSettings: {
 *             extraLabels: {
 *                 env: "prod",
 *             },
 *         },
 *         scrapeInterval: 300000000000,
 *         exporters: ["prometheus"],
 *     }),
 *     isPaused: false,
 * });
 * // Example: GCP Metrics DataIntegration
 * // For a full list of supported GCP metrics, visit the official GCP documentation:
 * // https://cloud.google.com/monitoring/api/metrics_gcp
 * const gcpExample = new groundcover.Dataintegration("gcpExample", {
 *     type: "gcpmetrics",
 *     config: JSON.stringify({
 *         name: "test-gcp",
 *         version: 1,
 *         enabled: true,
 *         targetServiceAccount: "demo@gcp-demo-project.iam.gserviceaccount.com",
 *         regions: ["us-west1"],
 *         metricPrefixes: [
 *             "cloudsql.googleapis.com",
 *             "compute.googleapis.com",
 *         ],
 *         projectIDs: ["gcp-demo-project"],
 *         scrapeInterval: 300000000000,
 *         exporters: ["prometheus"],
 *         labelSettings: {
 *             extraLabels: {
 *                 env: "prod",
 *             },
 *         },
 *     }),
 *     isPaused: false,
 * });
 * // Example: Azure Metrics DataIntegration
 * // For a full list of supported Azure metrics, visit the official Azure Monitor documentation:
 * // https://learn.microsoft.com/en-us/azure/azure-monitor/reference/metrics-index
 * const azureExample = new groundcover.Dataintegration("azureExample", {
 *     type: "azuremetrics",
 *     config: JSON.stringify({
 *         name: "Azure demo",
 *         version: 1,
 *         subscriptions: ["b3128f7e-54df-4d2e-9c3e-93a4f1f8c9a0"],
 *         regions: ["australiaeast"],
 *         azureMetrics: [{
 *             resourceType: "Microsoft.Compute/virtualMachines",
 *             metrics: [{
 *                 name: "Available Memory Bytes",
 *             }],
 *             aggregations: [
 *                 "Average",
 *                 "Maximum",
 *                 "Minimum",
 *             ],
 *         }],
 *         azureCloudEnvironment: "AzurePublicCloud",
 *         scrapeInterval: 300000000000,
 *         labelSettings: {
 *             extraLabels: {
 *                 env: "prod",
 *             },
 *         },
 *         exporters: ["prometheus"],
 *     }),
 *     isPaused: false,
 * });
 * export const cloudwatchDataintegrationId = cloudwatchExample.id;
 * export const gcpmetricsDataintegrationId = gcpExample.id;
 * export const azuremetricsDataintegrationId = azureExample.id;
 * ```
 */
export class Dataintegration extends pulumi.CustomResource {
    /**
     * Get an existing Dataintegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DataintegrationState, opts?: pulumi.CustomResourceOptions): Dataintegration {
        return new Dataintegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/dataintegration:Dataintegration';

    /**
     * Returns true if the given object is an instance of Dataintegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dataintegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dataintegration.__pulumiType;
    }

    /**
     * The cluster where the data integration runs. If unspecified, it will run in the backend.
     */
    declare public readonly cluster: pulumi.Output<string | undefined>;
    /**
     * The JSON configuration for the data integration.
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * Whether the data integration is paused. Default: `false`.
     */
    declare public readonly isPaused: pulumi.Output<boolean>;
    /**
     * The type of data integration (e.g., 'cloudwatch', etc.).
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * The last update timestamp of the data integration configuration.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The user who last updated the data integration configuration.
     */
    declare public /*out*/ readonly updatedBy: pulumi.Output<string>;

    /**
     * Create a Dataintegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataintegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DataintegrationArgs | DataintegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DataintegrationState | undefined;
            resourceInputs["cluster"] = state?.cluster;
            resourceInputs["config"] = state?.config;
            resourceInputs["isPaused"] = state?.isPaused;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["updatedBy"] = state?.updatedBy;
        } else {
            const args = argsOrState as DataintegrationArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["cluster"] = args?.cluster;
            resourceInputs["config"] = args?.config;
            resourceInputs["isPaused"] = args?.isPaused;
            resourceInputs["type"] = args?.type;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["updatedBy"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dataintegration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dataintegration resources.
 */
export interface DataintegrationState {
    /**
     * The cluster where the data integration runs. If unspecified, it will run in the backend.
     */
    cluster?: pulumi.Input<string>;
    /**
     * The JSON configuration for the data integration.
     */
    config?: pulumi.Input<string>;
    /**
     * Whether the data integration is paused. Default: `false`.
     */
    isPaused?: pulumi.Input<boolean>;
    /**
     * The type of data integration (e.g., 'cloudwatch', etc.).
     */
    type?: pulumi.Input<string>;
    /**
     * The last update timestamp of the data integration configuration.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * The user who last updated the data integration configuration.
     */
    updatedBy?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Dataintegration resource.
 */
export interface DataintegrationArgs {
    /**
     * The cluster where the data integration runs. If unspecified, it will run in the backend.
     */
    cluster?: pulumi.Input<string>;
    /**
     * The JSON configuration for the data integration.
     */
    config: pulumi.Input<string>;
    /**
     * Whether the data integration is paused. Default: `false`.
     */
    isPaused?: pulumi.Input<boolean>;
    /**
     * The type of data integration (e.g., 'cloudwatch', etc.).
     */
    type: pulumi.Input<string>;
}
