// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Logs Pipeline resource. This is a singleton resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * // Example Logs Pipeline
 * const logspipeline = new groundcover.Logspipeline("logspipeline", {value: `ottlRules:
 *   - ruleName: example-rule
 *     conditions:
 *       - container_name == "nginx"
 *     statements:
 *       - set(attributes["test.key"], "test-value")
 * `});
 * export const logsPipelineUpdatedAt = logspipeline.updatedAt;
 * ```
 */
export class Logspipeline extends pulumi.CustomResource {
    /**
     * Get an existing Logspipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogspipelineState, opts?: pulumi.CustomResourceOptions): Logspipeline {
        return new Logspipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/logspipeline:Logspipeline';

    /**
     * Returns true if the given object is an instance of Logspipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Logspipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Logspipeline.__pulumiType;
    }

    /**
     * The last update timestamp of the logs pipeline configuration.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The YAML representation of the logs pipeline configuration.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a Logspipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogspipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogspipelineArgs | LogspipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LogspipelineState | undefined;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["value"] = state?.value;
        } else {
            const args = argsOrState as LogspipelineArgs | undefined;
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["value"] = args?.value;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Logspipeline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Logspipeline resources.
 */
export interface LogspipelineState {
    /**
     * The last update timestamp of the logs pipeline configuration.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * The YAML representation of the logs pipeline configuration.
     */
    value?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Logspipeline resource.
 */
export interface LogspipelineArgs {
    /**
     * The YAML representation of the logs pipeline configuration.
     */
    value: pulumi.Input<string>;
}
