// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * groundcover Monitor resource managed via raw YAML.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * // Example Monitor: K8s Pod Crash Looping using monitor_yaml
 * const k8sPodCrashLooping = new groundcover.Monitor("k8sPodCrashLooping", {monitorYaml: `title: K8s Pod Crash Looping
 * display:
 *   header: K8s Pod Crash Looping
 *   resourceHeaderLabels:
 *   - workload
 *   contextHeaderLabels:
 *   - cluster
 *   - namespace
 *   - workload
 *   description: Kubernetes pod is on a CrashLoopBackOff for more than 5 minutes
 * severity: S2
 * measurementType: event
 * model:
 *   queries:
 *   - dataType: metrics
 *     name: threshold_input_query
 *     pipeline:
 *       function:
 *         name: avg_over_time
 *         pipelines:
 *         - function:
 *             name: avg_by
 *             pipelines:
 *             - metric: groundcover_kube_pod_container_status_waiting_reason
 *             args:
 *             - cluster
 *             - namespace
 *             - workload
 *         args:
 *         - 5m
 *     conditions:
 *     - key: reason
 *       origin: root
 *       type: string
 *       filters:
 *       - op: match
 *         value: CrashLoopBackOff
 *   thresholds:
 *   - name: threshold_1
 *     inputName: threshold_input_query
 *     operator: gt
 *     values:
 *     - 0
 * executionErrorState: OK
 * evaluationInterval:
 *   interval: 1m0s
 *   pendingFor: 5m0s
 * `});
 * export const monitorExampleId = k8sPodCrashLooping.id;
 * export const monitorExampleYamlOutput = k8sPodCrashLooping.monitorYaml;
 * ```
 */
export class Monitor extends pulumi.CustomResource {
    /**
     * Get an existing Monitor resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MonitorState, opts?: pulumi.CustomResourceOptions): Monitor {
        return new Monitor(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/monitor:Monitor';

    /**
     * Returns true if the given object is an instance of Monitor.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Monitor {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Monitor.__pulumiType;
    }

    /**
     * The monitor definition in YAML format.
     */
    declare public readonly monitorYaml: pulumi.Output<string>;

    /**
     * Create a Monitor resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MonitorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MonitorArgs | MonitorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MonitorState | undefined;
            resourceInputs["monitorYaml"] = state?.monitorYaml;
        } else {
            const args = argsOrState as MonitorArgs | undefined;
            if (args?.monitorYaml === undefined && !opts.urn) {
                throw new Error("Missing required property 'monitorYaml'");
            }
            resourceInputs["monitorYaml"] = args?.monitorYaml;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Monitor.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Monitor resources.
 */
export interface MonitorState {
    /**
     * The monitor definition in YAML format.
     */
    monitorYaml?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Monitor resource.
 */
export interface MonitorArgs {
    /**
     * The monitor definition in YAML format.
     */
    monitorYaml: pulumi.Input<string>;
}
