// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Notification Route resource for managing issue routing to connected apps.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * const slackWebhookUrl = config.require("slackWebhookUrl");
 * const pagerdutyRoutingKey = config.require("pagerdutyRoutingKey");
 * const slack = new groundcover.ConnectedApp("slack", {
 *     type: "slack-webhook",
 *     data: {
 *         url: slackWebhookUrl,
 *     },
 * });
 * const pagerduty = new groundcover.ConnectedApp("pagerduty", {
 *     type: "pagerduty",
 *     data: {
 *         routingKey: pagerdutyRoutingKey,
 *     },
 * });
 * const criticalAlerts = new groundcover.NotificationRoute("criticalAlerts", {
 *     query: "severity:critical",
 *     routes: [
 *         {
 *             status: ["Alerting"],
 *             connected_apps: [
 *                 {
 *                     type: "pagerduty",
 *                     id: pagerduty.id,
 *                 },
 *                 {
 *                     type: "slack-webhook",
 *                     id: slack.id,
 *                 },
 *             ],
 *         },
 *         {
 *             status: ["Resolved"],
 *             connected_apps: [{
 *                 type: "slack-webhook",
 *                 id: slack.id,
 *             }],
 *         },
 *     ],
 *     notificationSettings: {
 *         renotification_interval: "1h",
 *     },
 * });
 * const allAlertsToSlack = new groundcover.NotificationRoute("allAlertsToSlack", {
 *     query: "*",
 *     routes: [{
 *         status: [
 *             "Alerting",
 *             "Resolved",
 *         ],
 *         connected_apps: [{
 *             type: "slack-webhook",
 *             id: slack.id,
 *         }],
 *     }],
 *     notificationSettings: {
 *         renotification_interval: "30m",
 *     },
 * });
 * export const criticalRouteId = criticalAlerts.id;
 * export const allAlertsRouteId = allAlertsToSlack.id;
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import groundcover:index/notificationRoute:NotificationRoute example "<id>"
 * ```
 */
export class NotificationRoute extends pulumi.CustomResource {
    /**
     * Get an existing NotificationRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NotificationRouteState, opts?: pulumi.CustomResourceOptions): NotificationRoute {
        return new NotificationRoute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/notificationRoute:NotificationRoute';

    /**
     * Returns true if the given object is an instance of NotificationRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationRoute.__pulumiType;
    }

    /**
     * The date the notification route was created (RFC3339 format).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The user who created the notification route.
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<string>;
    /**
     * The date the notification route was last modified (RFC3339 format).
     */
    declare public /*out*/ readonly modifiedAt: pulumi.Output<string>;
    /**
     * The user who last modified the notification route.
     */
    declare public /*out*/ readonly modifiedBy: pulumi.Output<string>;
    /**
     * Name of the notification route.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Notification settings for this route.
     */
    declare public readonly notificationSettings: pulumi.Output<outputs.NotificationRouteNotificationSettings>;
    /**
     * gcQL query to match issues.
     */
    declare public readonly query: pulumi.Output<string>;
    /**
     * List of routing rules that define which connected apps receive notifications based on issue status.
     */
    declare public readonly routes: pulumi.Output<outputs.NotificationRouteRoute[]>;

    /**
     * Create a NotificationRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NotificationRouteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NotificationRouteArgs | NotificationRouteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NotificationRouteState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["modifiedAt"] = state?.modifiedAt;
            resourceInputs["modifiedBy"] = state?.modifiedBy;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationSettings"] = state?.notificationSettings;
            resourceInputs["query"] = state?.query;
            resourceInputs["routes"] = state?.routes;
        } else {
            const args = argsOrState as NotificationRouteArgs | undefined;
            if (args?.query === undefined && !opts.urn) {
                throw new Error("Missing required property 'query'");
            }
            if (args?.routes === undefined && !opts.urn) {
                throw new Error("Missing required property 'routes'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationSettings"] = args?.notificationSettings;
            resourceInputs["query"] = args?.query;
            resourceInputs["routes"] = args?.routes;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["modifiedAt"] = undefined /*out*/;
            resourceInputs["modifiedBy"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NotificationRoute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NotificationRoute resources.
 */
export interface NotificationRouteState {
    /**
     * The date the notification route was created (RFC3339 format).
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The user who created the notification route.
     */
    createdBy?: pulumi.Input<string>;
    /**
     * The date the notification route was last modified (RFC3339 format).
     */
    modifiedAt?: pulumi.Input<string>;
    /**
     * The user who last modified the notification route.
     */
    modifiedBy?: pulumi.Input<string>;
    /**
     * Name of the notification route.
     */
    name?: pulumi.Input<string>;
    /**
     * Notification settings for this route.
     */
    notificationSettings?: pulumi.Input<inputs.NotificationRouteNotificationSettings>;
    /**
     * gcQL query to match issues.
     */
    query?: pulumi.Input<string>;
    /**
     * List of routing rules that define which connected apps receive notifications based on issue status.
     */
    routes?: pulumi.Input<pulumi.Input<inputs.NotificationRouteRoute>[]>;
}

/**
 * The set of arguments for constructing a NotificationRoute resource.
 */
export interface NotificationRouteArgs {
    /**
     * Name of the notification route.
     */
    name?: pulumi.Input<string>;
    /**
     * Notification settings for this route.
     */
    notificationSettings?: pulumi.Input<inputs.NotificationRouteNotificationSettings>;
    /**
     * gcQL query to match issues.
     */
    query: pulumi.Input<string>;
    /**
     * List of routing rules that define which connected apps receive notifications based on issue status.
     */
    routes: pulumi.Input<pulumi.Input<inputs.NotificationRouteRoute>[]>;
}
