// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a groundcover RBAC policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@pulumiverse/groundcover";
 *
 * // Define a groundcover Policy
 * const myPolicy = new groundcover.Policy("myPolicy", {
 *     description: "This policy is managed by Terraform.",
 *     claimRole: "sso-admin-role",
 *     role: {
 *         admin: "admin",
 *     },
 *     dataScope: {
 *         simple: {
 *             operator: "and",
 *             conditions: [
 *                 {
 *                     key: "cluster",
 *                     origin: "root",
 *                     type: "string",
 *                     filters: [{
 *                         op: "match",
 *                         value: "production-cluster",
 *                     }],
 *                 },
 *                 {
 *                     key: "namespace",
 *                     origin: "root",
 *                     type: "string",
 *                     filters: [{
 *                         op: "not_match",
 *                         value: "kube-system",
 *                     }],
 *                 },
 *             ],
 *         },
 *     },
 * });
 * export const policyUuid = myPolicy.uuid;
 * export const policyRevisionNumber = myPolicy.revisionNumber;
 * ```
 */
export class Policy extends pulumi.CustomResource {
    /**
     * Get an existing Policy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyState, opts?: pulumi.CustomResourceOptions): Policy {
        return new Policy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/policy:Policy';

    /**
     * Returns true if the given object is an instance of Policy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Policy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Policy.__pulumiType;
    }

    /**
     * SSO Role claim name used for mapping.
     */
    declare public readonly claimRole: pulumi.Output<string | undefined>;
    /**
     * Defines the data scope restrictions for the policy. Either 'simple' or 'advanced' must be specified, but not both.
     */
    declare public readonly dataScope: pulumi.Output<outputs.PolicyDataScope | undefined>;
    /**
     * Indicates if the policy is deprecated.
     */
    declare public /*out*/ readonly deprecated: pulumi.Output<boolean>;
    /**
     * A description for the policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Indicates if the policy is system-defined.
     */
    declare public /*out*/ readonly isSystemDefined: pulumi.Output<boolean>;
    /**
     * The name of the policy.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Indicates if the policy is read-only (managed internally).
     */
    declare public /*out*/ readonly readOnly: pulumi.Output<boolean>;
    /**
     * Revision number of the policy, used for concurrency control.
     */
    declare public /*out*/ readonly revisionNumber: pulumi.Output<number>;
    /**
     * Role definitions associated with the policy. Maps role identifiers to specific permissions or access levels.
     */
    declare public readonly role: pulumi.Output<{[key: string]: string}>;
    /**
     * The unique identifier (UUID) of the policy.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Policy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyArgs | PolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyState | undefined;
            resourceInputs["claimRole"] = state?.claimRole;
            resourceInputs["dataScope"] = state?.dataScope;
            resourceInputs["deprecated"] = state?.deprecated;
            resourceInputs["description"] = state?.description;
            resourceInputs["isSystemDefined"] = state?.isSystemDefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["readOnly"] = state?.readOnly;
            resourceInputs["revisionNumber"] = state?.revisionNumber;
            resourceInputs["role"] = state?.role;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as PolicyArgs | undefined;
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["claimRole"] = args?.claimRole;
            resourceInputs["dataScope"] = args?.dataScope;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["role"] = args?.role;
            resourceInputs["deprecated"] = undefined /*out*/;
            resourceInputs["isSystemDefined"] = undefined /*out*/;
            resourceInputs["readOnly"] = undefined /*out*/;
            resourceInputs["revisionNumber"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Policy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Policy resources.
 */
export interface PolicyState {
    /**
     * SSO Role claim name used for mapping.
     */
    claimRole?: pulumi.Input<string>;
    /**
     * Defines the data scope restrictions for the policy. Either 'simple' or 'advanced' must be specified, but not both.
     */
    dataScope?: pulumi.Input<inputs.PolicyDataScope>;
    /**
     * Indicates if the policy is deprecated.
     */
    deprecated?: pulumi.Input<boolean>;
    /**
     * A description for the policy.
     */
    description?: pulumi.Input<string>;
    /**
     * Indicates if the policy is system-defined.
     */
    isSystemDefined?: pulumi.Input<boolean>;
    /**
     * The name of the policy.
     */
    name?: pulumi.Input<string>;
    /**
     * Indicates if the policy is read-only (managed internally).
     */
    readOnly?: pulumi.Input<boolean>;
    /**
     * Revision number of the policy, used for concurrency control.
     */
    revisionNumber?: pulumi.Input<number>;
    /**
     * Role definitions associated with the policy. Maps role identifiers to specific permissions or access levels.
     */
    role?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The unique identifier (UUID) of the policy.
     */
    uuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Policy resource.
 */
export interface PolicyArgs {
    /**
     * SSO Role claim name used for mapping.
     */
    claimRole?: pulumi.Input<string>;
    /**
     * Defines the data scope restrictions for the policy. Either 'simple' or 'advanced' must be specified, but not both.
     */
    dataScope?: pulumi.Input<inputs.PolicyDataScope>;
    /**
     * A description for the policy.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the policy.
     */
    name?: pulumi.Input<string>;
    /**
     * Role definitions associated with the policy. Maps role identifiers to specific permissions or access levels.
     */
    role: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
