// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a groundcover Recurring Silence.
 *
 * Recurring silences allow you to automatically suppress alerts on a repeating schedule based on matching criteria. This is useful for planned maintenance windows, recurring deployments, or other predictable situations where you want to regularly mute alerts.
 *
 * A recurring silence is defined by: a recurrence schedule (daily, weekly, or monthly), a time window (start_time, end_time) in a specific timezone, an optional comment, and one or more matchers that define which alerts to silence.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * // Example 1: Daily recurring silence for nightly maintenance
 * // Silences alerts every day from 2 AM to 4 AM UTC
 * const nightlyMaintenance = new groundcover.RecurringSilence("nightlyMaintenance", {
 *     comment: "Nightly maintenance window for payment-service",
 *     recurrenceType: "daily",
 *     startTime: "02:00",
 *     endTime: "04:00",
 *     timezone: "UTC",
 *     matchers: [{
 *         name: "service",
 *         value: "payment-service",
 *         is_equal: true,
 *         is_contains: false,
 *     }],
 * });
 * // Example 2: Weekly recurring silence for deployment windows
 * // Silences alerts every Monday and Wednesday from 9 AM to 11 AM Eastern
 * const deploymentWindow = new groundcover.RecurringSilence("deploymentWindow", {
 *     comment: "Scheduled deployment window",
 *     recurrenceType: "weekly",
 *     startTime: "09:00",
 *     endTime: "11:00",
 *     timezone: "America/New_York",
 *     daysOfWeeks: [
 *         1,
 *         3,
 *     ],
 *     matchers: [
 *         {
 *             name: "workload",
 *             value: "api-gateway",
 *             is_equal: true,
 *             is_contains: false,
 *         },
 *         {
 *             name: "environment",
 *             value: "staging",
 *             is_equal: true,
 *             is_contains: false,
 *         },
 *     ],
 * });
 * // Example 3: Monthly recurring silence with contains pattern
 * // Silences alerts on the 1st and 15th of each month from 10 PM to 6 AM (overnight)
 * const patchDay = new groundcover.RecurringSilence("patchDay", {
 *     comment: "Monthly patch day - overnight maintenance",
 *     recurrenceType: "monthly",
 *     startTime: "22:00",
 *     endTime: "06:00",
 *     timezone: "Europe/London",
 *     daysOfMonths: [
 *         1,
 *         15,
 *     ],
 *     matchers: [{
 *         name: "service",
 *         value: "app-dev",
 *         is_equal: true,
 *         is_contains: true,
 *     }],
 * });
 * // Example 4: Disabled recurring silence with negation (is_equal = false)
 * // Silences all alerts EXCEPT for production environment
 * const weekendSilence = new groundcover.RecurringSilence("weekendSilence", {
 *     comment: "Weekend silence - currently disabled",
 *     recurrenceType: "weekly",
 *     startTime: "00:00",
 *     endTime: "23:59",
 *     timezone: "UTC",
 *     daysOfWeeks: [
 *         0,
 *         6,
 *     ],
 *     enabled: false,
 *     matchers: [{
 *         name: "environment",
 *         value: "production",
 *         is_equal: false,
 *         is_contains: false,
 *     }],
 * });
 * export const nightlyMaintenanceId = nightlyMaintenance.id;
 * export const deploymentWindowId = deploymentWindow.id;
 * ```
 */
export class RecurringSilence extends pulumi.CustomResource {
    /**
     * Get an existing RecurringSilence resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RecurringSilenceState, opts?: pulumi.CustomResourceOptions): RecurringSilence {
        return new RecurringSilence(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/recurringSilence:RecurringSilence';

    /**
     * Returns true if the given object is an instance of RecurringSilence.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RecurringSilence {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RecurringSilence.__pulumiType;
    }

    /**
     * A comment describing the reason for the recurring silence.
     */
    declare public readonly comment: pulumi.Output<string>;
    /**
     * Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
     */
    declare public readonly daysOfMonths: pulumi.Output<number[] | undefined>;
    /**
     * Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
     */
    declare public readonly daysOfWeeks: pulumi.Output<number[] | undefined>;
    /**
     * Whether the recurring silence is enabled. Defaults to `true`.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
     */
    declare public readonly endTime: pulumi.Output<string>;
    /**
     * A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
     */
    declare public readonly matchers: pulumi.Output<outputs.RecurringSilenceMatcher[]>;
    /**
     * The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
     */
    declare public readonly recurrenceType: pulumi.Output<string>;
    /**
     * The start time of the silence window in `HH:MM` format (e.g., `09:00`).
     */
    declare public readonly startTime: pulumi.Output<string>;
    /**
     * The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
     */
    declare public readonly timezone: pulumi.Output<string>;

    /**
     * Create a RecurringSilence resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RecurringSilenceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RecurringSilenceArgs | RecurringSilenceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RecurringSilenceState | undefined;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["daysOfMonths"] = state?.daysOfMonths;
            resourceInputs["daysOfWeeks"] = state?.daysOfWeeks;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["endTime"] = state?.endTime;
            resourceInputs["matchers"] = state?.matchers;
            resourceInputs["recurrenceType"] = state?.recurrenceType;
            resourceInputs["startTime"] = state?.startTime;
            resourceInputs["timezone"] = state?.timezone;
        } else {
            const args = argsOrState as RecurringSilenceArgs | undefined;
            if (args?.endTime === undefined && !opts.urn) {
                throw new Error("Missing required property 'endTime'");
            }
            if (args?.matchers === undefined && !opts.urn) {
                throw new Error("Missing required property 'matchers'");
            }
            if (args?.recurrenceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'recurrenceType'");
            }
            if (args?.startTime === undefined && !opts.urn) {
                throw new Error("Missing required property 'startTime'");
            }
            if (args?.timezone === undefined && !opts.urn) {
                throw new Error("Missing required property 'timezone'");
            }
            resourceInputs["comment"] = args?.comment;
            resourceInputs["daysOfMonths"] = args?.daysOfMonths;
            resourceInputs["daysOfWeeks"] = args?.daysOfWeeks;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["endTime"] = args?.endTime;
            resourceInputs["matchers"] = args?.matchers;
            resourceInputs["recurrenceType"] = args?.recurrenceType;
            resourceInputs["startTime"] = args?.startTime;
            resourceInputs["timezone"] = args?.timezone;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RecurringSilence.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RecurringSilence resources.
 */
export interface RecurringSilenceState {
    /**
     * A comment describing the reason for the recurring silence.
     */
    comment?: pulumi.Input<string>;
    /**
     * Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
     */
    daysOfMonths?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
     */
    daysOfWeeks?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Whether the recurring silence is enabled. Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
     */
    endTime?: pulumi.Input<string>;
    /**
     * A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
     */
    matchers?: pulumi.Input<pulumi.Input<inputs.RecurringSilenceMatcher>[]>;
    /**
     * The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
     */
    recurrenceType?: pulumi.Input<string>;
    /**
     * The start time of the silence window in `HH:MM` format (e.g., `09:00`).
     */
    startTime?: pulumi.Input<string>;
    /**
     * The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
     */
    timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RecurringSilence resource.
 */
export interface RecurringSilenceArgs {
    /**
     * A comment describing the reason for the recurring silence.
     */
    comment?: pulumi.Input<string>;
    /**
     * Days of the month when the silence should be active (1-31). Required when `recurrenceType` is `monthly`.
     */
    daysOfMonths?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Days of the week when the silence should be active (0=Sunday, 1=Monday, ..., 6=Saturday). Required when `recurrenceType` is `weekly`.
     */
    daysOfWeeks?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Whether the recurring silence is enabled. Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * The end time of the silence window in `HH:MM` format (e.g., `17:00`). Can be before startTime to indicate an overnight window (e.g., `22:00` to `06:00`).
     */
    endTime: pulumi.Input<string>;
    /**
     * A list of matchers that define which alerts to silence. Each matcher specifies a label name and value to match against.
     */
    matchers: pulumi.Input<pulumi.Input<inputs.RecurringSilenceMatcher>[]>;
    /**
     * The recurrence type. Must be one of: `daily`, `weekly`, `monthly`.
     */
    recurrenceType: pulumi.Input<string>;
    /**
     * The start time of the silence window in `HH:MM` format (e.g., `09:00`).
     */
    startTime: pulumi.Input<string>;
    /**
     * The IANA timezone name for the silence window (e.g., `America/New_York`, `UTC`).
     */
    timezone: pulumi.Input<string>;
}
