// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as groundcover from "@groundcover-com/groundcover";
 *
 * const config = new pulumi.Config();
 * const groundcoverApiKey = config.require("groundcoverApiKey");
 * const groundcoverBackendId = config.require("groundcoverBackendId");
 * const externalApiKey = config.require("externalApiKey");
 * const databasePassword = config.require("databasePassword");
 * // Example: Create an API key secret
 * const apiKeyExample = new groundcover.Secret("apiKeyExample", {
 *     type: "api_key",
 *     content: externalApiKey,
 * });
 * // Example: Create a password secret
 * const passwordExample = new groundcover.Secret("passwordExample", {
 *     type: "password",
 *     content: databasePassword,
 * });
 * // The secret ID can be used in other resources like data integrations
 * // For example:
 * // resource "groundcover_dataintegration" "example" {
 * //   type = "prometheus"
 * //   config = jsonencode({
 * //     endpoint = "https://prometheus.example.com"
 * //     password = groundcover_secret.password_example.id  # Use secret reference
 * //   })
 * // }
 * export const apiKeySecretId = apiKeyExample.id;
 * export const passwordSecretId = passwordExample.id;
 * ```
 */
export class Secret extends pulumi.CustomResource {
    /**
     * Get an existing Secret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretState, opts?: pulumi.CustomResourceOptions): Secret {
        return new Secret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'groundcover:index/secret:Secret';

    /**
     * Returns true if the given object is an instance of Secret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Secret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Secret.__pulumiType;
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The secret content/value. This is write-only and will not be returned by the API.
     */
    declare public readonly content: pulumi.Output<string>;
    /**
     * The name of the secret.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The type of the secret. Valid values are: `apiKey`, `password`, `basicAuth`.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a Secret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretArgs | SecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretState | undefined;
            resourceInputs["content"] = state?.content;
            resourceInputs["name"] = state?.name;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as SecretArgs | undefined;
            if (args?.content === undefined && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["content"] = args?.content ? pulumi.secret(args.content) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["content"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Secret.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Secret resources.
 */
export interface SecretState {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The secret content/value. This is write-only and will not be returned by the API.
     */
    content?: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    name?: pulumi.Input<string>;
    /**
     * The type of the secret. Valid values are: `apiKey`, `password`, `basicAuth`.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Secret resource.
 */
export interface SecretArgs {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The secret content/value. This is write-only and will not be returned by the API.
     */
    content: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    name?: pulumi.Input<string>;
    /**
     * The type of the secret. Valid values are: `apiKey`, `password`, `basicAuth`.
     */
    type: pulumi.Input<string>;
}
